Unreal Engine 5.6 C++ API: FPhysxUserData Struct Reference
FPhysxUserData Struct Reference
PhysX user data.
#include "PhysxUserData.h"
Public Member Functions
FPhysxUserData ()
FPhysxUserData (FBodyInstance *InPayload)
FPhysxUserData (FConstraintInstance *InPayload)
FPhysxUserData (FCustomPhysXPayload *InPayload)
FPhysxUserData (FKShapeElem *InPayload)
FPhysxUserData (FPhysScene *InPayload)
FPhysxUserData (UPhysicalMaterial *InPayload)
FPhysxUserData (UPrimitiveComponent *InPayload)
template<>
FORCEINLINE FBodyInstance * Get (void *UserData)
template<>
FORCEINLINE UPhysicalMaterial * Get (void *UserData)
template<>
FORCEINLINE FPhysScene * Get (void *UserData)
template<>
FORCEINLINE FConstraintInstance * Get (void *UserData)
template<>
FORCEINLINE UPrimitiveComponent * Get (void *UserData)
template<>
FORCEINLINE FKShapeElem * Get (void *UserData)
template<>
FORCEINLINE FCustomPhysXPayload * Get (void *UserData)
template<>
FORCEINLINE void Set (void *UserData, FBodyInstance *Payload)
template<>
FORCEINLINE void Set (void *UserData, FConstraintInstance *Payload)
template<>
FORCEINLINE void Set (void *UserData, FCustomPhysXPayload *Payload)
template<>
FORCEINLINE void Set (void *UserData, FKShapeElem *Payload)
template<>
FORCEINLINE void Set (void *UserData, FPhysScene *Payload)
template<>
FORCEINLINE void Set (void *UserData, UPhysicalMaterial *Payload)
template<>
FORCEINLINE void Set (void *UserData, UPrimitiveComponent *Payload)
Static Public Member Functions
template<class T>
static T * Get (void *UserData)
static bool IsGarbage (void *UserData)
template<class T>
static void Set (void *UserData, T *Payload)
Protected Attributes
void * Payload
EPhysxUserDataType::Type Type
Detailed Description
PhysX user data.
Definition at line 36 of file PhysxUserData.h.
Constructor & Destructor Documentation
FPhysxUserData() [1/8]
FPhysxUserData::FPhysxUserData () inline
Definition at line 43 of file PhysxUserData.h.
References Invalid, Payload, and Type.
Referenced by Get(), IsGarbage(), Set(), Set(), Set(), Set(), Set(), Set(), and Set().
FPhysxUserData() [2/8]
FPhysxUserData::FPhysxUserData (FBodyInstance * InPayload) inline
Definition at line 44 of file PhysxUserData.h.
References Payload, and Type.
FPhysxUserData() [3/8]
FPhysxUserData::FPhysxUserData (UPhysicalMaterial * InPayload) inline
Definition at line 45 of file PhysxUserData.h.
References Payload, and Type.
FPhysxUserData() [4/8]
FPhysxUserData::FPhysxUserData (FPhysScene * InPayload) inline
Definition at line 46 of file PhysxUserData.h.
References Payload, and Type.
FPhysxUserData() [5/8]
FPhysxUserData::FPhysxUserData (FConstraintInstance * InPayload) inline
Definition at line 47 of file PhysxUserData.h.
References Payload, and Type.
FPhysxUserData() [6/8]
FPhysxUserData::FPhysxUserData (UPrimitiveComponent * InPayload) inline
Definition at line 48 of file PhysxUserData.h.
References Payload, and Type.
FPhysxUserData() [7/8]
FPhysxUserData::FPhysxUserData (FKShapeElem * InPayload) inline
Definition at line 49 of file PhysxUserData.h.
References Payload, and Type.
FPhysxUserData() [8/8]
FPhysxUserData::FPhysxUserData (FCustomPhysXPayload * InPayload) inline
Definition at line 50 of file PhysxUserData.h.
References Payload, and Type.
Member Function Documentation
Get() [1/8]
template<class T> T * FPhysxUserData::Get (void * UserData) static
Get() [2/8]
template<> FORCEINLINE FBodyInstance * FPhysxUserData::Get (void * UserData)
Definition at line 59 of file PhysxUserData.h.
References FPhysxUserData(), EPhysxUserDataType::BodyInstance, FORCEINLINE, and Type.
Get() [3/8]
template<> FORCEINLINE UPhysicalMaterial * FPhysxUserData::Get (void * UserData)
Definition at line 60 of file PhysxUserData.h.
References FPhysxUserData(), FORCEINLINE, EPhysxUserDataType::PhysicalMaterial, and Type.
Get() [4/8]
template<> FORCEINLINE FPhysScene * FPhysxUserData::Get (void * UserData)
Definition at line 61 of file PhysxUserData.h.
References FPhysxUserData(), FORCEINLINE, EPhysxUserDataType::PhysScene, and Type.
Get() [5/8]
template<> FORCEINLINE FConstraintInstance * FPhysxUserData::Get (void * UserData)
Definition at line 62 of file PhysxUserData.h.
References FPhysxUserData(), EPhysxUserDataType::ConstraintInstance, FORCEINLINE, and Type.
Get() [6/8]
template<> FORCEINLINE UPrimitiveComponent * FPhysxUserData::Get (void * UserData)
Definition at line 63 of file PhysxUserData.h.
References FPhysxUserData(), FORCEINLINE, EPhysxUserDataType::PrimitiveComponent, and Type.
Get() [7/8]
template<> FORCEINLINE FKShapeElem * FPhysxUserData::Get (void * UserData)
Definition at line 64 of file PhysxUserData.h.
References FPhysxUserData(), EPhysxUserDataType::AggShape, FORCEINLINE, and Type.
Get() [8/8]
template<> FORCEINLINE FCustomPhysXPayload * FPhysxUserData::Get (void * UserData)
Definition at line 65 of file PhysxUserData.h.
References FPhysxUserData(), EPhysxUserDataType::CustomPayload, FORCEINLINE, and Type.
IsGarbage()
bool FPhysxUserData::IsGarbage (void * UserData) inline static
Definition at line 56 of file PhysxUserData.h.
References FPhysxUserData(), EPhysxUserDataType::CustomPayload, and EPhysxUserDataType::Invalid.
Set() [1/8]
template<> FORCEINLINE void FPhysxUserData::Set (void * UserData, FBodyInstance * Payload)
Definition at line 67 of file PhysxUserData.h.
References FPhysxUserData(), EPhysxUserDataType::BodyInstance, check, FORCEINLINE, and Payload.
Set() [2/8]
template<> FORCEINLINE void FPhysxUserData::Set (void * UserData, FConstraintInstance * Payload)
Definition at line 70 of file PhysxUserData.h.
References FPhysxUserData(), check, EPhysxUserDataType::ConstraintInstance, FORCEINLINE, and Payload.
Set() [3/8]
template<> FORCEINLINE void FPhysxUserData::Set (void * UserData, FCustomPhysXPayload * Payload)
Definition at line 73 of file PhysxUserData.h.
References FPhysxUserData(), check, EPhysxUserDataType::CustomPayload, FORCEINLINE, and Payload.
Set() [4/8]
template<> FORCEINLINE void FPhysxUserData::Set (void * UserData, FKShapeElem * Payload)
Definition at line 72 of file PhysxUserData.h.
References FPhysxUserData(), EPhysxUserDataType::AggShape, check, FORCEINLINE, and Payload.
Set() [5/8]
template<> FORCEINLINE void FPhysxUserData::Set (void * UserData, FPhysScene * Payload)
Definition at line 69 of file PhysxUserData.h.
References FPhysxUserData(), check, FORCEINLINE, Payload, and EPhysxUserDataType::PhysScene.
Set() [6/8]
template<class T> void FPhysxUserData::Set (void * UserData, T * Payload) static
References Payload.
Set() [7/8]
template<> FORCEINLINE void FPhysxUserData::Set (void * UserData, UPhysicalMaterial * Payload)
Definition at line 68 of file PhysxUserData.h.
References FPhysxUserData(), check, FORCEINLINE, Payload, and EPhysxUserDataType::PhysicalMaterial.
Set() [8/8]
template<> FORCEINLINE void FPhysxUserData::Set (void * UserData, UPrimitiveComponent * Payload)
Definition at line 71 of file PhysxUserData.h.
References FPhysxUserData(), check, FORCEINLINE, Payload, and EPhysxUserDataType::PrimitiveComponent.
Field Documentation
Payload
void* FPhysxUserData::Payload protected
Definition at line 40 of file PhysxUserData.h.
Referenced by FPhysxUserData(), FPhysxUserData(), FPhysxUserData(), FPhysxUserData(), FPhysxUserData(), FPhysxUserData(), FPhysxUserData(), FPhysxUserData(), Set(), Set(), Set(), Set(), Set(), Set(), Set(), and Set().
Type
EPhysxUserDataType::Type FPhysxUserData::Type protected
Definition at line 39 of file PhysxUserData.h.
Referenced by FPhysxUserData(), FPhysxUserData(), FPhysxUserData(), FPhysxUserData(), FPhysxUserData(), FPhysxUserData(), FPhysxUserData(), FPhysxUserData(), and Get().
The documentation for this struct was generated from the following file:
PhysxUserData.h