Unreal Engine 5.6 C++ API: UE::Tasks::Private::FTaskBase Class Reference
UE::Tasks::Private::FTaskBase Class Reference abstract
#include "TaskPrivate.h"
Data Structures
class FPrerequisites
class FSubsequents
Public Member Functions
void AddNested (FTaskBase &Nested)
template<typename HigherLevelTaskType, decltype(std::declval< HigherLevelTaskType >().Pimpl) * = nullptr>
bool AddPrerequisites (const HigherLevelTaskType &Prerequisite)
template<typename HigherLevelTaskType, std::enable_if_t< std::is_same_v< HigherLevelTaskType, FGraphEventRef > > * = nullptr>
bool AddPrerequisites (const HigherLevelTaskType &Prerequisite)
template<typename PrerequisiteCollectionType, decltype(std::declval< PrerequisiteCollectionType >().begin()) * = nullptr>
void AddPrerequisites (const PrerequisiteCollectionType &InPrerequisites)
bool AddPrerequisites (FTaskBase &Prerequisite)
void AddRef ()
bool AddSubsequent (FTaskBase &Subsequent)
EExtendedTaskPriority GetExtendedPriority () const
FPipe * GetPipe () const
ETaskPriority GetPriority () const
uint32 GetRefCount (std::memory_order MemoryOrder=std::memory_order_relaxed) const
TaskTrace::FId GetTraceId () const
bool IsAwaitable () const
bool IsCompleted () const
bool IsNamedThreadTask () const
void Release ()
void ReleaseInternalReference ()
void SetPipe (FPipe &InPipe)
bool TryLaunch (uint64 TaskSize)
bool TryRetractAndExecute (FTimeout Timeout, uint32 RecursionDepth=0)
template<typename ConditionType>
UE_DEPRECATED (5.5, "This method will be removed.") bool BusyWait(ConditionType &&Condition)
UE_DEPRECATED (5.5, "Use Wait instead") bool BusyWait(FTimeout Timeout)
void Wait ()
bool Wait (FTimeout Timeout)
void WaitWithNamedThreadsSupport ()
Protected Member Functions
FTaskBase (uint32 InitRefCount, bool bUnlockPrerequisites=true)
virtual ~FTaskBase ()
template<typename PrerequisiteCollectionType, decltype(std::declval< PrerequisiteCollectionType >().begin()) * = nullptr>
void AddPrerequisites (const PrerequisiteCollectionType &InPrerequisites, bool bLockPrerequisite)
void ClearPipe ()
void Close ()
virtual void ExecuteTask ()=0
void Init (const TCHAR *InDebugName, ETaskPriority InPriority, EExtendedTaskPriority InExtendedPriority, ETaskFlags Flags)
bool TryExecuteTask ()
void UnlockPrerequisites ()
Private Member Functions
void FinishPipeExecution ()
void ReleasePrerequisites ()
void Schedule (bool &bWakeUpWorker)
void StartPipeExecution ()
FTaskBase * TryPushIntoPipe ()
bool TrySetExecutionFlag ()
bool TryUnlock (bool &bWakeUpWorker)
UE_NONCOPYABLE (FTaskBase)
bool WaitImpl (FTimeout Timeout)
Private Member Functions inherited from UE::FInheritedContextBase
void CaptureInheritedContext ()
FInheritedContextScope RestoreInheritedContext ()
Private Attributes
std::atomic< uint32 > ExecutingThreadId = FThread::InvalidThreadId
EExtendedTaskPriority ExtendedPriority
LowLevelTasks::FTask LowLevelTask
std::atomic< uint32 > NumLocks { NumInitialLocks }
FPipe * Pipe { nullptr }
FPrerequisites< TInlineAllocator< 1 > > Prerequisites
std::atomic< uint32 > RefCount
FEventCount StateChangeEvent
FSubsequents< TInlineAllocator< 1 > > Subsequents
Static Private Attributes
static constexpr uint32 ExecutionFlag = 0x80000000
static constexpr uint32 NumInitialLocks = 1
Detailed Description
Definition at line 119 of file TaskPrivate.h.
Constructor & Destructor Documentation
FTaskBase()
UE::Tasks::Private::FTaskBase::FTaskBase (uint32 InitRefCount, bool bUnlockPrerequisites = true) inline explicit protected
Definition at line 157 of file TaskPrivate.h.
References Prerequisites, and RefCount.
Referenced by FBaseGraphTask::FBaseGraphTask(), UE::Tasks::Private::FTaskEventBase::FTaskEventBase(), UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, typename TEnableIf< std::is_same_v< TInvokeResult_T< TaskBodyType >, void > >::Type >::TExecutableTaskBase(), UE::Tasks::Private::TTaskWithResult< ResultType >::TTaskWithResult(), AddNested(), AddPrerequisites(), AddPrerequisites(), AddSubsequent(), Close(), UE::Tasks::Private::FTaskBase::FPrerequisites< AllocatorType >::Push(), UE::Tasks::Private::FTaskBase::FSubsequents< AllocatorType >::PushIfNotClosed(), UE::Tasks::Private::FTaskBase::FPrerequisites< AllocatorType >::PushNoLock(), ReleasePrerequisites(), TryExecuteTask(), TryPushIntoPipe(), TryUnlock(), and UE_NONCOPYABLE().
~FTaskBase()
virtual UE::Tasks::Private::FTaskBase::~FTaskBase () inline protected virtual
Definition at line 193 of file TaskPrivate.h.
References check, TaskTrace::Destroyed(), GetTraceId(), and UE::Tasks::Private::IsCompleted().
Member Function Documentation
AddNested()
void UE::Tasks::Private::FTaskBase::AddNested (FTaskBase & Nested) inline
Definition at line 429 of file TaskPrivate.h.
References FTaskBase(), AddNested(), checkf, ExecutionFlag, NumLocks, Prerequisites, TASKGRAPH_VERBOSE_EVENT_SCOPE, and TEXT.
Referenced by AddNested(), and FBaseGraphTask::DontCompleteUntil().
AddPrerequisites() [1/5]
template<typename HigherLevelTaskType, decltype(std::declval< HigherLevelTaskType >().Pimpl) * = nullptr> bool UE::Tasks::Private::FTaskBase::AddPrerequisites (const HigherLevelTaskType & Prerequisite) inline
Definition at line 256 of file TaskPrivate.h.
References AddPrerequisites().
AddPrerequisites() [2/5]
template<typename HigherLevelTaskType, std::enable_if_t< std::is_same_v< HigherLevelTaskType, FGraphEventRef > > * = nullptr> bool UE::Tasks::Private::FTaskBase::AddPrerequisites (const HigherLevelTaskType & Prerequisite) inline
Definition at line 264 of file TaskPrivate.h.
References AddPrerequisites().
AddPrerequisites() [3/5]
template<typename PrerequisiteCollectionType, decltype(std::declval< PrerequisiteCollectionType >().begin()) * = nullptr> void UE::Tasks::Private::FTaskBase::AddPrerequisites (const PrerequisiteCollectionType & InPrerequisites) inline
Definition at line 360 of file TaskPrivate.h.
References AddPrerequisites().
AddPrerequisites() [4/5]
template<typename PrerequisiteCollectionType, decltype(std::declval< PrerequisiteCollectionType >().begin()) * = nullptr> void UE::Tasks::Private::FTaskBase::AddPrerequisites (const PrerequisiteCollectionType & InPrerequisites, bool bLockPrerequisite) inline protected
Definition at line 274 of file TaskPrivate.h.
References FTaskBase(), AddRef(), AddSubsequent(), checkf, ExecutionFlag, GetNum(), NumInitialLocks, NumLocks, Prerequisites, TASKGRAPH_VERBOSE_EVENT_SCOPE, TEXT, and UNLIKELY.
AddPrerequisites() [5/5]
bool UE::Tasks::Private::FTaskBase::AddPrerequisites (FTaskBase & Prerequisite) inline
Definition at line 227 of file TaskPrivate.h.
References FTaskBase(), AddRef(), AddSubsequent(), checkf, ExecutionFlag, NumInitialLocks, NumLocks, Prerequisites, TASKGRAPH_VERBOSE_EVENT_SCOPE, and TEXT.
Referenced by FBaseGraphTask::FBaseGraphTask(), AddPrerequisites(), AddPrerequisites(), and FBaseGraphTask::DontCompleteUntil().
AddRef()
void UE::Tasks::Private::FTaskBase::AddRef () inline
Definition at line 131 of file TaskPrivate.h.
References RefCount.
Referenced by AddPrerequisites(), AddPrerequisites(), TryExecuteTask(), and FBaseGraphTask::Unlock().
AddSubsequent()
bool UE::Tasks::Private::FTaskBase::AddSubsequent (FTaskBase & Subsequent) inline
Definition at line 367 of file TaskPrivate.h.
References FTaskBase(), GetTraceId(), TaskTrace::SubsequentAdded(), and Subsequents.
Referenced by AddPrerequisites(), and AddPrerequisites().
ClearPipe()
void UE::Tasks::Private::FTaskBase::ClearPipe () protected
Referenced by Close().
Close()
void UE::Tasks::Private::FTaskBase::Close () inline protected
Definition at line 552 of file TaskPrivate.h.
References FTaskBase(), checkSlow, ClearPipe(), Close(), TaskTrace::Completed(), ExtendedPriority, GetPipe(), GetTraceId(), UE::Tasks::Private::IsCompleted(), ReleasePrerequisites(), StateChangeEvent, Subsequents, UE::Tasks::TaskEvent, and TASKGRAPH_VERBOSE_EVENT_SCOPE.
Referenced by Close(), TryExecuteTask(), and TryUnlock().
ExecuteTask()
virtual void UE::Tasks::Private::FTaskBase::ExecuteTask () protected pure virtual
Implemented in FGraphEventImpl, TGraphTask< TTask >, UE::Tasks::Private::FTaskEventBase, UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, ResultType, Enable >, and UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, typename TEnableIf< std::is_same_v< TInvokeResult_T< TaskBodyType >, void > >::Type >.
Referenced by TryExecuteTask().
FinishPipeExecution()
void UE::Tasks::Private::FTaskBase::FinishPipeExecution () private
Referenced by TryExecuteTask().
GetExtendedPriority()
EExtendedTaskPriority UE::Tasks::Private::FTaskBase::GetExtendedPriority () const inline
Definition at line 219 of file TaskPrivate.h.
References ExtendedPriority.
Referenced by FBaseGraphTask::IsTaskEvent().
GetPipe()
FPipe * UE::Tasks::Private::FTaskBase::GetPipe () const inline
Definition at line 387 of file TaskPrivate.h.
References Pipe.
Referenced by Close(), TryExecuteTask(), and TryUnlock().
GetPriority()
ETaskPriority UE::Tasks::Private::FTaskBase::GetPriority () const inline
Definition at line 214 of file TaskPrivate.h.
References LowLevelTask.
GetRefCount()
uint32 UE::Tasks::Private::FTaskBase::GetRefCount (std::memory_order MemoryOrder = std::memory_order_relaxed) const inline
Definition at line 147 of file TaskPrivate.h.
References RefCount.
GetTraceId()
TaskTrace::FId UE::Tasks::Private::FTaskBase::GetTraceId () const inline
Definition at line 488 of file TaskPrivate.h.
References TaskTrace::InvalidId.
Referenced by FGraphEventImpl::FGraphEventImpl(), UE::Tasks::Private::FTaskEventBase::FTaskEventBase(), ~FTaskBase(), AddSubsequent(), Close(), TGraphTask< TTask >::FConstructor::ConstructAndHold(), TryExecuteTask(), TryLaunch(), and UE_DEPRECATED().
Init()
void UE::Tasks::Private::FTaskBase::Init (const TCHAR * InDebugName, ETaskPriority InPriority, EExtendedTaskPriority InExtendedPriority, ETaskFlags Flags) inline protected
Definition at line 166 of file TaskPrivate.h.
References UE::FInheritedContextBase::CaptureInheritedContext(), UE::Tasks::DoNotRunInsideBusyWait, ExtendedPriority, Flags, LowLevelTask, and TryExecuteTask().
IsAwaitable()
bool UE::Tasks::Private::FTaskBase::IsAwaitable () const inline
Definition at line 204 of file TaskPrivate.h.
References ExecutingThreadId, and FAndroidTLS::GetCurrentThreadId().
IsCompleted()
bool UE::Tasks::Private::FTaskBase::IsCompleted () const inline
Definition at line 409 of file TaskPrivate.h.
References Subsequents.
Referenced by UE::Tasks::Private::TTaskWithResult< ResultType >::GetResult(), and FBaseGraphTask::IsComplete().
IsNamedThreadTask()
bool UE::Tasks::Private::FTaskBase::IsNamedThreadTask () const inline
Definition at line 209 of file TaskPrivate.h.
References ExtendedPriority, and UE::Tasks::GameThreadNormalPri.
Referenced by FBaseGraphTask::Execute().
Release()
void UE::Tasks::Private::FTaskBase::Release () inline
Definition at line 136 of file TaskPrivate.h.
References RefCount.
Referenced by TryExecuteTask(), and TryUnlock().
ReleaseInternalReference()
void UE::Tasks::Private::FTaskBase::ReleaseInternalReference () inline
Definition at line 423 of file TaskPrivate.h.
References LowLevelTask, and verify.
Referenced by FBaseGraphTask::Execute(), and TryUnlock().
ReleasePrerequisites()
void UE::Tasks::Private::FTaskBase::ReleasePrerequisites () inline private
Definition at line 700 of file TaskPrivate.h.
References FTaskBase(), Prerequisites, ReleasePrerequisites(), and TASKGRAPH_VERBOSE_EVENT_SCOPE.
Referenced by Close(), ReleasePrerequisites(), TryExecuteTask(), and TryUnlock().
Schedule()
void UE::Tasks::Private::FTaskBase::Schedule (bool & bWakeUpWorker) private
Referenced by TryUnlock().
SetPipe()
void UE::Tasks::Private::FTaskBase::SetPipe (FPipe & InPipe) inline
Definition at line 380 of file TaskPrivate.h.
References NumLocks, and Pipe.
StartPipeExecution()
void UE::Tasks::Private::FTaskBase::StartPipeExecution () private
Referenced by TryExecuteTask().
TryExecuteTask()
bool UE::Tasks::Private::FTaskBase::TryExecuteTask () inline protected
Definition at line 501 of file TaskPrivate.h.
References FTaskBase(), AddRef(), Close(), UE::Tasks::Private::ExchangeCurrentTask(), ExecuteTask(), ExecutingThreadId, ExecutionFlag, FinishPipeExecution(), FAndroidTLS::GetCurrentThreadId(), GetPipe(), GetTraceId(), FThread::InvalidThreadId, NumLocks, Release(), ReleasePrerequisites(), UE::FInheritedContextBase::RestoreInheritedContext(), StartPipeExecution(), TASKGRAPH_VERBOSE_EVENT_SCOPE, TryExecuteTask(), and TrySetExecutionFlag().
Referenced by FBaseGraphTask::Execute(), Init(), TryExecuteTask(), and TryUnlock().
TryLaunch()
bool UE::Tasks::Private::FTaskBase::TryLaunch (uint64 TaskSize) inline
Definition at line 394 of file TaskPrivate.h.
References ExtendedPriority, GetTraceId(), TaskTrace::Launched(), LowLevelTask, UE::Tasks::Private::TranslatePriority(), and TryUnlock().
Referenced by FBaseGraphTask::Unlock().
TryPushIntoPipe()
FTaskBase * UE::Tasks::Private::FTaskBase::TryPushIntoPipe () private
References FTaskBase().
Referenced by TryUnlock().
TryRetractAndExecute()
bool UE::Tasks::Private::FTaskBase::TryRetractAndExecute (FTimeout Timeout, uint32 RecursionDepth = 0)
References UE::Tasks::Timeout.
TrySetExecutionFlag()
bool UE::Tasks::Private::FTaskBase::TrySetExecutionFlag () inline private
Definition at line 692 of file TaskPrivate.h.
References ExecutionFlag, and NumLocks.
Referenced by TryExecuteTask(), and TryUnlock().
TryUnlock()
bool UE::Tasks::Private::FTaskBase::TryUnlock (bool & bWakeUpWorker) inline private
Definition at line 590 of file TaskPrivate.h.
References FTaskBase(), checkf, Close(), ExecutionFlag, ExtendedPriority, GetPipe(), UE::Tasks::Inline, NumLocks, Prerequisites, Release(), ReleaseInternalReference(), ReleasePrerequisites(), Schedule(), UE::Tasks::TaskEvent, TASKGRAPH_VERBOSE_EVENT_SCOPE, TEXT, TryExecuteTask(), TryPushIntoPipe(), TrySetExecutionFlag(), and TryUnlock().
Referenced by TryLaunch(), and TryUnlock().
UE_DEPRECATED() [1/2]
template<typename ConditionType> UE::Tasks::Private::FTaskBase::UE_DEPRECATED (5. 5, "This method will be removed.") && inline
Definition at line 473 of file TaskPrivate.h.
References bool, Forward(), GetTraceId(), UE::Tasks::Private::IsCompleted(), UE::FTimeout::Never(), TRACE_CPUPROFILER_EVENT_SCOPE, and UE::Tasks::Private::TryRetractAndExecute().
UE_DEPRECATED() [2/2]
UE::Tasks::Private::FTaskBase::UE_DEPRECATED (5. 5, "Use Wait instead") inline
Definition at line 465 of file TaskPrivate.h.
References bool, UE::Tasks::Timeout, and UE::Tasks::Wait().
UE_NONCOPYABLE()
UE::Tasks::Private::FTaskBase::UE_NONCOPYABLE (FTaskBase) private
References FTaskBase().
UnlockPrerequisites()
void UE::Tasks::Private::FTaskBase::UnlockPrerequisites () inline protected
Definition at line 831 of file TaskPrivate.h.
References Prerequisites.
Referenced by FBaseGraphTask::FBaseGraphTask().
Wait() [1/2]
void UE::Tasks::Private::FTaskBase::Wait ()
Wait() [2/2]
bool UE::Tasks::Private::FTaskBase::Wait (FTimeout Timeout)
References UE::Tasks::Timeout.
WaitImpl()
bool UE::Tasks::Private::FTaskBase::WaitImpl (FTimeout Timeout) private
References UE::Tasks::Timeout.
WaitWithNamedThreadsSupport()
void UE::Tasks::Private::FTaskBase::WaitWithNamedThreadsSupport ()
Field Documentation
ExecutingThreadId
std::atomic<uint32> UE::Tasks::Private::FTaskBase::ExecutingThreadId = FThread::InvalidThreadId private
Definition at line 730 of file TaskPrivate.h.
Referenced by IsAwaitable(), and TryExecuteTask().
ExecutionFlag
uint32 UE::Tasks::Private::FTaskBase::ExecutionFlag = 0x80000000 static constexpr private
Definition at line 126 of file TaskPrivate.h.
Referenced by AddNested(), AddPrerequisites(), AddPrerequisites(), TryExecuteTask(), TrySetExecutionFlag(), and TryUnlock().
ExtendedPriority
EExtendedTaskPriority UE::Tasks::Private::FTaskBase::ExtendedPriority private
Definition at line 728 of file TaskPrivate.h.
Referenced by Close(), GetExtendedPriority(), Init(), IsNamedThreadTask(), TryLaunch(), and TryUnlock().
LowLevelTask
LowLevelTasks::FTask UE::Tasks::Private::FTaskBase::LowLevelTask private
Definition at line 782 of file TaskPrivate.h.
Referenced by GetPriority(), Init(), ReleaseInternalReference(), and TryLaunch().
NumInitialLocks
uint32 UE::Tasks::Private::FTaskBase::NumInitialLocks = 1 static constexpr private
Definition at line 721 of file TaskPrivate.h.
Referenced by AddPrerequisites(), and AddPrerequisites().
NumLocks
std::atomic<uint32> UE::Tasks::Private::FTaskBase::NumLocks { NumInitialLocks } private
Definition at line 722 of file TaskPrivate.h.
Referenced by AddNested(), AddPrerequisites(), AddPrerequisites(), SetPipe(), TryExecuteTask(), TrySetExecutionFlag(), and TryUnlock().
Pipe
FPipe* UE::Tasks::Private::FTaskBase::Pipe { nullptr } private
Definition at line 724 of file TaskPrivate.h.
Referenced by GetPipe(), and SetPipe().
Prerequisites
FPrerequisites<TInlineAllocator<1> > UE::Tasks::Private::FTaskBase::Prerequisites private
Definition at line 780 of file TaskPrivate.h.
Referenced by FTaskBase(), AddNested(), AddPrerequisites(), AddPrerequisites(), TGraphTask< TTask >::CreateTask(), ReleasePrerequisites(), TryUnlock(), and UnlockPrerequisites().
RefCount
std::atomic<uint32> UE::Tasks::Private::FTaskBase::RefCount private
Definition at line 153 of file TaskPrivate.h.
Referenced by FTaskBase(), AddRef(), GetRefCount(), and Release().
StateChangeEvent
FEventCount UE::Tasks::Private::FTaskBase::StateChangeEvent private
Definition at line 726 of file TaskPrivate.h.
Referenced by Close().
Subsequents
FSubsequents<TInlineAllocator<1> > UE::Tasks::Private::FTaskBase::Subsequents private
Definition at line 827 of file TaskPrivate.h.
Referenced by AddSubsequent(), Close(), and IsCompleted().
The documentation for this class was generated from the following file:
TaskPrivate.h