Unreal Engine 5.6 C++ API: TFieldPath< PropertyType > Struct Template Reference
TFieldPath< PropertyType > Struct Template Reference
#include "FieldPath.h"
Public Member Functions
TFieldPath ()
FORCEINLINE TFieldPath (const TCHAR *InPath)
Construct from a string.
FORCEINLINE TFieldPath (const TFieldPath &Other)
template<typename OtherPropertyType UE_REQUIRES>
FORCEINLINE TFieldPath (const TFieldPath< OtherPropertyType > &Other)
Construct from another weak pointer of another type, intended for derived-to-base conversions.
template<typename OtherPropertyType UE_REQUIRES>
FORCEINLINE TFieldPath (OtherPropertyType *InProperty, EDummy1=Dummy1)
Construct from an object pointer.
FORCEINLINE TFieldPath (TYPE_OF_NULLPTR)
Construct from a null pointer.
FORCEINLINE PropertyType * Get (UStruct *InCurrentStruct=nullptr) const
Gets the field represented by this TFieldPath.
FORCEINLINE PropertyType * operator* () const
Dereference the weak pointer.
FORCEINLINE PropertyType * operator-> () const
Dereference the weak pointer.
FORCEINLINE TFieldPath & operator= (const TFieldPath &Other)
template<typename OtherPropertyType UE_REQUIRES>
FORCEINLINE void operator= (const TFieldPath< OtherPropertyType > &Other)
Assign from another weak pointer, intended for derived-to-base conversions.
template<typename OtherPropertyType UE_REQUIRES>
FORCEINLINE void operator= (OtherPropertyType *InProperty)
Copy from an object pointer.
FORCEINLINE PropertyType * ResolveWithRenamedStructPackage (UStruct *InCurrentStruct)
Public Member Functions inherited from FFieldPath
FFieldPath ()=default
FFieldPath (FField *InField)
void Generate (const TCHAR *InFieldPathString)
Generates path from the passed in field pointer.
void Generate (FField *InField)
Generates path from the passed in field pointer.
FORCEINLINE FField * GetTyped (FFieldClass *ExpectedType, UStruct *InCurrentStruct=nullptr) const
Gets the field represented by this FFieldPath.
bool IsPathToFieldEmpty () const
Returns true if the field path is empty (does not test if the owner is valid) This is usually used to verify if the reason behind this field being unresolved is because the owner is missing or the property couldn't be found.
bool IsStale () const
Slightly different than !IsValid(), returns true if this used to point to a FField, but doesn't any more and has not been assigned or reset in the mean time.
FORCEINLINE bool operator!= (const FFieldPath &InOther) const
FORCEINLINE bool operator== (const FFieldPath &InOther) const
void Reset ()
Reset the weak pointer back to the NULL state.
FORCEINLINE void ResolveField (FFieldClass *ExpectedClass=FField::StaticClass(), UStruct *InCurrentStruct=nullptr, EPathResolveType InResolveType=FFieldPath::UseStructIfOuterNotFound) const
Tries to resolve the path and caches the result.
FString ToString () const
FField * TryToResolvePath (UStruct *InCurrentStruct, EPathResolveType InResolveType=FFieldPath::UseStructIfOuterNotFound) const
Tries to resolve the path without caching the resolved pointer.
Private Types
enum EDummy1 { Dummy1 }
Additional Inherited Members
Protected Types inherited from FFieldPath
enum EPathResolveType { UseStructIfOuterNotFound = 0 , UseStructAlways = 1 }
Protected Member Functions inherited from FFieldPath
FORCEINLINE void ClearCachedField () const
Clears the cached value so that the next time Get() is called, it will be resolved again.
FORCEINLINE bool NeedsResolving () const
Protected Attributes inherited from FFieldPath
TArray< FName > Path
Path to the FField object from the innermost FField to the outermost UObject (UPackage)
FField * ResolvedField = nullptr
Untracked pointer to the resolved property.
TWeakObjectPtr< UStruct > ResolvedOwner
The cached owner of this field.
Detailed Description
template<class PropertyType>
struct TFieldPath< PropertyType >
Definition at line 282 of file FieldPath.h.
Member Enumeration Documentation
EDummy1
template<class PropertyType> enum TFieldPath::EDummy1 private
Enumerator
Dummy1
Definition at line 287 of file FieldPath.h.
Constructor & Destructor Documentation
TFieldPath() [1/6]
template<class PropertyType> TFieldPath< PropertyType >::TFieldPath () inline
Definition at line 290 of file FieldPath.h.
TFieldPath() [2/6]
template<class PropertyType> FORCEINLINE TFieldPath< PropertyType >::TFieldPath (const TFieldPath< PropertyType > & Other) inline
Definition at line 292 of file FieldPath.h.
TFieldPath() [3/6]
template<class PropertyType> FORCEINLINE TFieldPath< PropertyType >::TFieldPath (TYPE_OF_NULLPTR) inline
Construct from a null pointer.
Definition at line 311 of file FieldPath.h.
TFieldPath() [4/6]
template<class PropertyType> FORCEINLINE TFieldPath< PropertyType >::TFieldPath (const TCHAR * InPath) inline
Construct from a string.
Definition at line 319 of file FieldPath.h.
TFieldPath() [5/6]
template<class PropertyType> template<typename OtherPropertyType UE_REQUIRES> FORCEINLINE TFieldPath< PropertyType >::TFieldPath (OtherPropertyType * InProperty, EDummy1 = Dummy1) inline
Construct from an object pointer.
Parameters
Object object to create a weak pointer to
Definition at line 343 of file FieldPath.h.
TFieldPath() [6/6]
template<class PropertyType> template<typename OtherPropertyType UE_REQUIRES> FORCEINLINE TFieldPath< PropertyType >::TFieldPath (const TFieldPath< OtherPropertyType > & Other) inline
Construct from another weak pointer of another type, intended for derived-to-base conversions.
Parameters
Other weak pointer to copy from
Definition at line 359 of file FieldPath.h.
Member Function Documentation
Get()
template<class PropertyType> FORCEINLINE PropertyType * TFieldPath< PropertyType >::Get (UStruct * InCurrentStruct = nullptr) const inline
Gets the field represented by this TFieldPath.
Parameters
InCurrentStruct Struct that's trying to resolve this field path
Returns
Field represented by this FFieldPath or null if it couldn't be resolved
Definition at line 405 of file FieldPath.h.
Referenced by TListTypeTraits< TFieldPath< T > >::DebugDump(), TListTypeTraits< TFieldPath< T > >::IsPtrValid(), TFieldPath< T >::operator*(), TFieldPath< T >::operator->(), FPropertyProxyArchive::operator<<(), operator==(), and operator==().
operator*()
template<class PropertyType> FORCEINLINE PropertyType * TFieldPath< PropertyType >::operator* () const inline
Dereference the weak pointer.
Definition at line 420 of file FieldPath.h.
operator->()
template<class PropertyType> FORCEINLINE PropertyType * TFieldPath< PropertyType >::operator-> () const inline
Dereference the weak pointer.
Definition at line 428 of file FieldPath.h.
operator=() [1/3]
template<class PropertyType> FORCEINLINE TFieldPath & TFieldPath< PropertyType >::operator= (const TFieldPath< PropertyType > & Other) inline
Definition at line 299 of file FieldPath.h.
operator=() [2/3]
template<class PropertyType> template<typename OtherPropertyType UE_REQUIRES> FORCEINLINE void TFieldPath< PropertyType >::operator= (const TFieldPath< OtherPropertyType > & Other) inline
Assign from another weak pointer, intended for derived-to-base conversions.
Parameters
Other weak pointer to copy from
Definition at line 391 of file FieldPath.h.
operator=() [3/3]
template<class PropertyType> template<typename OtherPropertyType UE_REQUIRES> FORCEINLINE void TFieldPath< PropertyType >::operator= (OtherPropertyType * InProperty) inline
Copy from an object pointer.
Parameters
Object object to create a weak pointer to
Definition at line 375 of file FieldPath.h.
ResolveWithRenamedStructPackage()
template<class PropertyType> FORCEINLINE PropertyType * TFieldPath< PropertyType >::ResolveWithRenamedStructPackage (UStruct * InCurrentStruct) inline
Definition at line 410 of file FieldPath.h.
The documentation for this struct was generated from the following file:
FieldPath.h