Unreal Engine 5.6 C++ API: FMeshElementTypeWrapper Class Reference
FMeshElementTypeWrapper Class Reference
This is a wrapper for a FMeshElementChannels.
#include "MeshElementContainer.h"
Public Member Functions
FMeshElementTypeWrapper (const FMeshElementTypeWrapper &Other)
Copy constructor - make a deep copy of the MeshElementType through the TUniquePtr.
FMeshElementTypeWrapper (const int32 NumberOfChannels=1)
Default constructor - construct a MeshElementType, optionally with more than one channel.
FMeshElementTypeWrapper (FMeshElementTypeWrapper &&)=default
Default move constructor.
FMeshElementChannels * Get ()
const FMeshElementChannels * Get () const
Transparent access through the TUniquePtr.
FMeshElementChannels & operator* ()
const FMeshElementChannels & operator* () const
FMeshElementChannels * operator-> ()
const FMeshElementChannels * operator-> () const
FMeshElementTypeWrapper & operator= (const FMeshElementTypeWrapper &Other)
Copy assignment.
FMeshElementTypeWrapper & operator= (FMeshElementTypeWrapper &&)=default
Default move assignment.
Private Attributes
TUniquePtr< FMeshElementChannels > Ptr
Friends
FArchive & operator<< (FArchive &Ar, FMeshElementTypeWrapper &Wrapper)
Serializer.
Detailed Description
This is a wrapper for a FMeshElementChannels.
It holds a TUniquePtr pointing to the actual FMeshElementChannels, so that its address is constant and can be cached.
Definition at line 428 of file MeshElementContainer.h.
Constructor & Destructor Documentation
FMeshElementTypeWrapper() [1/3]
FMeshElementTypeWrapper::FMeshElementTypeWrapper (const int32 NumberOfChannels = 1) inline explicit
Default constructor - construct a MeshElementType, optionally with more than one channel.
Definition at line 432 of file MeshElementContainer.h.
References check, MakeUnique(), and Ptr.
Referenced by FMeshElementTypeWrapper(), FMeshElementTypeWrapper(), operator<<, operator=(), and operator=().
FMeshElementTypeWrapper() [2/3]
FMeshElementTypeWrapper::FMeshElementTypeWrapper (const FMeshElementTypeWrapper & Other) inline
Copy constructor - make a deep copy of the MeshElementType through the TUniquePtr.
Definition at line 439 of file MeshElementContainer.h.
References FMeshElementTypeWrapper(), check, MakeUnique(), Other, and Ptr.
FMeshElementTypeWrapper() [3/3]
FMeshElementTypeWrapper::FMeshElementTypeWrapper (FMeshElementTypeWrapper &&) default
Default move constructor.
References FMeshElementTypeWrapper().
Member Function Documentation
Get() [1/2]
FMeshElementChannels * FMeshElementTypeWrapper::Get () inline
Definition at line 463 of file MeshElementContainer.h.
References Ptr.
Get() [2/2]
const FMeshElementChannels * FMeshElementTypeWrapper::Get () const inline
Transparent access through the TUniquePtr.
Definition at line 460 of file MeshElementContainer.h.
References Ptr.
operator*() [1/2]
FMeshElementChannels & FMeshElementTypeWrapper::operator* () inline
Definition at line 465 of file MeshElementContainer.h.
References Ptr.
operator*() [2/2]
const FMeshElementChannels & FMeshElementTypeWrapper::operator* () const inline
Definition at line 462 of file MeshElementContainer.h.
References Ptr.
operator->() [1/2]
FMeshElementChannels * FMeshElementTypeWrapper::operator-> () inline
Definition at line 464 of file MeshElementContainer.h.
References Ptr.
operator->() [2/2]
const FMeshElementChannels * FMeshElementTypeWrapper::operator-> () const inline
Definition at line 461 of file MeshElementContainer.h.
References Ptr.
operator=() [1/2]
FMeshElementTypeWrapper & FMeshElementTypeWrapper::operator= (const FMeshElementTypeWrapper & Other) inline
Copy assignment.
Definition at line 446 of file MeshElementContainer.h.
References FMeshElementTypeWrapper(), Other, and Swap.
operator=() [2/2]
FMeshElementTypeWrapper & FMeshElementTypeWrapper::operator= (FMeshElementTypeWrapper &&) default
Default move assignment.
References FMeshElementTypeWrapper().
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FMeshElementTypeWrapper & Wrapper) friend
Serializer.
Definition at line 468 of file MeshElementContainer.h.
References FMeshElementTypeWrapper(), Ar, and Ptr.
Field Documentation
Ptr
TUniquePtr<FMeshElementChannels> FMeshElementTypeWrapper::Ptr private
Definition at line 475 of file MeshElementContainer.h.
Referenced by FMeshElementTypeWrapper(), FMeshElementTypeWrapper(), Get(), Get(), operator*(), operator*(), operator->(), operator->(), and operator<<.
The documentation for this class was generated from the following file:
MeshElementContainer.h