Unreal Engine 5.6 C++ API: TNonNullPtr< TObjectPtr< ObjectType > > Class Template Reference
TNonNullPtr< TObjectPtr< ObjectType > > Class Template Reference
#include "ObjectPtr.h"
Public Types
using IntrusiveUnsetOptionalStateType
Public Member Functions
template<typename OtherObjectType UE_REQUIRES>
FORCEINLINE TNonNullPtr (const TNonNullPtr< OtherObjectType > &Other)
Constructs a non-null pointer from another non-null pointer.
FORCEINLINE TNonNullPtr (EDefaultConstructNonNullPtr)
FORCEINLINE TNonNullPtr (TObjectPtr< ObjectType > InObject)
Constructs a non-null pointer from the provided pointer.
FORCEINLINE TNonNullPtr (TYPE_OF_NULLPTR)
nullptr constructor - not allowed.
FORCEINLINE ObjectType * Get () const
Returns the internal pointer.
FORCEINLINE TObjectPtr< ObjectType > & GetRef ()
FORCEINLINE const TObjectPtr< ObjectType > & GetRef () const
FORCEINLINE bool IsInitialized () const
operator bool () const =delete
Use IsInitialized if needed.
FORCEINLINE operator ObjectType * () const
Returns the internal pointer.
FORCEINLINE bool operator!= (const TNonNullPtr &Other) const
FORCEINLINE ObjectType & operator* () const
Dereference operator returns a reference to the object this pointer points to.
FORCEINLINE ObjectType * operator-> () const
Arrow operator returns a pointer to this pointer's object.
template<typename OtherObjectType UE_REQUIRES>
FORCEINLINE TNonNullPtr & operator= (const TNonNullPtr< OtherObjectType > &Other)
Assignment operator taking another TNonNullPtr.
FORCEINLINE TNonNullPtr & operator= (ObjectType *InObject)
Assignment operator taking a pointer.
FORCEINLINE TNonNullPtr & operator= (TYPE_OF_NULLPTR)
Assignment operator taking a nullptr - not allowed.
FORCEINLINE bool operator== (const TNonNullPtr &Other) const
Comparison, will also handle default constructed state.
Static Public Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState
Private Attributes
TObjectPtr< ObjectType > Object
The object we're holding a reference to.
Friends
FORCEINLINE uint32 GetTypeHash (const TNonNullPtr &InPtr)
Detailed Description
template<typename ObjectType>
class TNonNullPtr< TObjectPtr< ObjectType > >
Definition at line 1808 of file ObjectPtr.h.
Member Typedef Documentation
IntrusiveUnsetOptionalStateType
using TNonNullPtr< ObjectType >::IntrusiveUnsetOptionalStateType
Definition at line 233 of file NonNullPointer.h.
Constructor & Destructor Documentation
TNonNullPtr() [1/4]
template<typename ObjectType> FORCEINLINE TNonNullPtr< TObjectPtr< ObjectType > >::TNonNullPtr (EDefaultConstructNonNullPtr) inline nodiscard
Definition at line 1812 of file ObjectPtr.h.
References FORCEINLINE, and Object.
Referenced by TNonNullPtr(), GetTypeHash, operator=(), operator=(), and operator=().
TNonNullPtr() [2/4]
template<typename ObjectType> FORCEINLINE TNonNullPtr< TObjectPtr< ObjectType > >::TNonNullPtr (TYPE_OF_NULLPTR) inline nodiscard
nullptr constructor - not allowed.
Definition at line 1820 of file ObjectPtr.h.
References FORCEINLINE.
TNonNullPtr() [3/4]
template<typename ObjectType> FORCEINLINE TNonNullPtr< TObjectPtr< ObjectType > >::TNonNullPtr (TObjectPtr< ObjectType > InObject) inline nodiscard
Constructs a non-null pointer from the provided pointer.
Must not be nullptr.
Definition at line 1829 of file ObjectPtr.h.
References ensureAlwaysMsgf, FORCEINLINE, Object, and TEXT.
TNonNullPtr() [4/4]
template<typename ObjectType> template<typename OtherObjectType UE_REQUIRES> FORCEINLINE TNonNullPtr< TObjectPtr< ObjectType > >::TNonNullPtr (const TNonNullPtr< OtherObjectType > & Other) inline nodiscard
Constructs a non-null pointer from another non-null pointer.
Definition at line 1842 of file ObjectPtr.h.
References TNonNullPtr(), FORCEINLINE, Object, and Other.
Member Function Documentation
Get()
template<typename ObjectType> FORCEINLINE ObjectType * TNonNullPtr< TObjectPtr< ObjectType > >::Get () const inline nodiscard
Returns the internal pointer.
Definition at line 1892 of file ObjectPtr.h.
References ensureMsgf, FORCEINLINE, Object, and TEXT.
GetRef() [1/2]
template<typename ObjectType> FORCEINLINE TObjectPtr< ObjectType > & TNonNullPtr< TObjectPtr< ObjectType > >::GetRef () inline nodiscard
Definition at line 1922 of file ObjectPtr.h.
References ensureMsgf, FORCEINLINE, Object, and TEXT.
GetRef() [2/2]
template<typename ObjectType> FORCEINLINE const TObjectPtr< ObjectType > & TNonNullPtr< TObjectPtr< ObjectType > >::GetRef () const inline nodiscard
Definition at line 1916 of file ObjectPtr.h.
References ensureMsgf, FORCEINLINE, Object, and TEXT.
IsInitialized()
template<typename ObjectType> FORCEINLINE bool TNonNullPtr< TObjectPtr< ObjectType > >::IsInitialized () const inline nodiscard
Definition at line 1928 of file ObjectPtr.h.
References FORCEINLINE, and Object.
operator bool()
template<typename ObjectType> TNonNullPtr< TObjectPtr< ObjectType > >::operator bool () const explicit delete
Use IsInitialized if needed.
operator ObjectType *()
template<typename ObjectType> FORCEINLINE TNonNullPtr< TObjectPtr< ObjectType > >::operator ObjectType * () const inline nodiscard
Returns the internal pointer.
Definition at line 1883 of file ObjectPtr.h.
References ensureMsgf, FORCEINLINE, Object, and TEXT.
operator!=()
FORCEINLINE bool TNonNullPtr< ObjectType >::operator!= (const TNonNullPtr< TObjectPtr< ObjectType > > & Other) const inline
Definition at line 134 of file NonNullPointer.h.
operator*()
template<typename ObjectType> FORCEINLINE ObjectType & TNonNullPtr< TObjectPtr< ObjectType > >::operator* () const inline nodiscard
Dereference operator returns a reference to the object this pointer points to.
Definition at line 1901 of file ObjectPtr.h.
References ensureMsgf, FORCEINLINE, Object, and TEXT.
operator->()
template<typename ObjectType> FORCEINLINE ObjectType * TNonNullPtr< TObjectPtr< ObjectType > >::operator-> () const inline nodiscard
Arrow operator returns a pointer to this pointer's object.
Definition at line 1910 of file ObjectPtr.h.
References ensureMsgf, FORCEINLINE, Object, and TEXT.
operator=() [1/3]
template<typename ObjectType> template<typename OtherObjectType UE_REQUIRES> FORCEINLINE TNonNullPtr & TNonNullPtr< TObjectPtr< ObjectType > >::operator= (const TNonNullPtr< OtherObjectType > & Other) inline
Assignment operator taking another TNonNullPtr.
Definition at line 1874 of file ObjectPtr.h.
References TNonNullPtr(), FORCEINLINE, Object, and Other.
operator=() [2/3]
template<typename ObjectType> FORCEINLINE TNonNullPtr & TNonNullPtr< TObjectPtr< ObjectType > >::operator= (ObjectType * InObject) inline
Assignment operator taking a pointer.
Definition at line 1860 of file ObjectPtr.h.
References TNonNullPtr(), ensureMsgf, FORCEINLINE, Object, and TEXT.
operator=() [3/3]
template<typename ObjectType> FORCEINLINE TNonNullPtr & TNonNullPtr< TObjectPtr< ObjectType > >::operator= (TYPE_OF_NULLPTR) inline
Assignment operator taking a nullptr - not allowed.
Definition at line 1850 of file ObjectPtr.h.
References TNonNullPtr(), and FORCEINLINE.
operator==()
FORCEINLINE bool TNonNullPtr< ObjectType >::operator== (const TNonNullPtr< TObjectPtr< ObjectType > > & Other) const inline
Comparison, will also handle default constructed state.
Definition at line 129 of file NonNullPointer.h.
Friends And Related Symbol Documentation
GetTypeHash
template<typename ObjectType> FORCEINLINE uint32 GetTypeHash (const TNonNullPtr< TObjectPtr< ObjectType > > & InPtr) friend
Definition at line 1939 of file ObjectPtr.h.
References TNonNullPtr(), FORCEINLINE, TNonNullPtr< ObjectType >::GetTypeHash, and TNonNullPtr< ObjectType >::Object.
Field Documentation
bHasIntrusiveUnsetOptionalState
bool TNonNullPtr< ObjectType >::bHasIntrusiveUnsetOptionalState static constexpr
Definition at line 232 of file NonNullPointer.h.
Object
template<typename ObjectType> TObjectPtr<ObjectType> TNonNullPtr< TObjectPtr< ObjectType > >::Object private
The object we're holding a reference to.
Definition at line 1945 of file ObjectPtr.h.
Referenced by TNonNullPtr(), TNonNullPtr(), TNonNullPtr(), Get(), GetRef(), GetRef(), IsInitialized(), operator ObjectType *(), operator*(), operator->(), operator=(), and operator=().
The documentation for this class was generated from the following file:
ObjectPtr.h