Unreal Engine 5.6 C++ API: FCurveOwnerInterface Class Reference
FCurveOwnerInterface Class Reference abstract
Interface you implement if you want the CurveEditor to be able to edit curves on you.
#include "CurveOwnerInterface.h"
Public Member Functions
virtual ~FCurveOwnerInterface ()
virtual FLinearColor GetClampedLinearColorValue (float InTime) const
Evaluate this color curve at the specified time.
virtual FLinearColor GetCurveColor (FRichCurveEditInfo CurveInfo) const
virtual TArray< FRichCurveEditInfoConst > GetCurves () const =0
Returns set of curves to edit.
virtual TArray< FRichCurveEditInfo > GetCurves ()=0
Returns set of curves to query.
virtual FLinearColor GetLinearColorValue (float InTime) const
Evaluate this color curve at the specified time.
virtual TArray< const UObject * > GetOwners () const =0
Returns the owner(s) of the curve.
virtual bool HasAnyAlphaKeys () const
virtual bool HasRichCurves () const
Whether the curves returned by GetCurves are rich or simple curves.
virtual bool IsLinearColorCurve () const
Whether the curve represents a linear color.
virtual bool IsValidCurve (FRichCurveEditInfo CurveInfo)=0
Validates that a previously retrieved curve is still valid for editing.
virtual void MakeTransactional ()=0
Called to make curve owner transactional.
virtual void ModifyOwner ()=0
Called to modify the owner of the curve.
virtual void ModifyOwnerChange ()
Called to modify the owner of the curve during interaction/while being edited.
virtual void OnCurveChanged (const TArray< FRichCurveEditInfo > &ChangedCurveEditInfos)=0
Called when any of the curves have been changed.
virtual bool RepointCurveOwner (const FPackageReloadedEvent &InPackageReloadedEvent, FCurveOwnerInterface *&OutNewCurveOwner) const
Called during package reload to repoint a curve interface asset.
Static Protected Member Functions
template<typename AssetType>
static bool RepointCurveOwnerAsset (const FPackageReloadedEvent &InPackageReloadedEvent, const AssetType *InCurveOwnerAsset, FCurveOwnerInterface *&OutNewCurveOwner)
Default implementation of RepointCurveOwner that can be used with UObject based types that inherit FCurveOwnerInterface.
Detailed Description
Interface you implement if you want the CurveEditor to be able to edit curves on you.
Definition at line 12 of file CurveOwnerInterface.h.
Constructor & Destructor Documentation
~FCurveOwnerInterface()
virtual FCurveOwnerInterface::~FCurveOwnerInterface () inline virtual
Definition at line 16 of file CurveOwnerInterface.h.
Member Function Documentation
GetClampedLinearColorValue()
virtual FLinearColor FCurveOwnerInterface::GetClampedLinearColorValue (float InTime) const inline virtual
Evaluate this color curve at the specified time.
Definition at line 58 of file CurveOwnerInterface.h.
References FLinearColor::Black, and InTime.
GetCurveColor()
virtual FLinearColor FCurveOwnerInterface::GetCurveColor (FRichCurveEditInfo CurveInfo) const virtual
Returns
Color for this curve
GetCurves() [1/2]
virtual TArray< FRichCurveEditInfoConst > FCurveOwnerInterface::GetCurves () const pure virtual
Returns set of curves to edit.
Must not release the curves while being edited.
Implemented in SRigVMGraphPinCurveFloat.
GetCurves() [2/2]
virtual TArray< FRichCurveEditInfo > FCurveOwnerInterface::GetCurves () pure virtual
Returns set of curves to query.
Must not release the curves while being edited.
Implemented in SRigVMGraphPinCurveFloat.
GetLinearColorValue()
virtual FLinearColor FCurveOwnerInterface::GetLinearColorValue (float InTime) const inline virtual
Evaluate this color curve at the specified time.
Definition at line 52 of file CurveOwnerInterface.h.
References FLinearColor::Black, and InTime.
GetOwners()
virtual TArray< const UObject * > FCurveOwnerInterface::GetOwners () const pure virtual
Returns the owner(s) of the curve.
Implemented in SRigVMGraphPinCurveFloat.
HasAnyAlphaKeys()
virtual bool FCurveOwnerInterface::HasAnyAlphaKeys () const inline virtual
Returns
True if the curve has any alpha keys
Definition at line 64 of file CurveOwnerInterface.h.
HasRichCurves()
virtual bool FCurveOwnerInterface::HasRichCurves () const inline virtual
Whether the curves returned by GetCurves are rich or simple curves.
Definition at line 46 of file CurveOwnerInterface.h.
IsLinearColorCurve()
virtual bool FCurveOwnerInterface::IsLinearColorCurve () const inline virtual
Whether the curve represents a linear color.
Definition at line 40 of file CurveOwnerInterface.h.
IsValidCurve()
virtual bool FCurveOwnerInterface::IsValidCurve (FRichCurveEditInfo CurveInfo) pure virtual
Validates that a previously retrieved curve is still valid for editing.
Implemented in SRigVMGraphPinCurveFloat.
MakeTransactional()
virtual void FCurveOwnerInterface::MakeTransactional () pure virtual
Called to make curve owner transactional.
Implemented in SRigVMGraphPinCurveFloat.
ModifyOwner()
virtual void FCurveOwnerInterface::ModifyOwner () pure virtual
Called to modify the owner of the curve.
Implemented in SRigVMGraphPinCurveFloat.
Referenced by ModifyOwnerChange().
ModifyOwnerChange()
virtual void FCurveOwnerInterface::ModifyOwnerChange () inline virtual
Called to modify the owner of the curve during interaction/while being edited.
Definition at line 28 of file CurveOwnerInterface.h.
References ModifyOwner().
OnCurveChanged()
virtual void FCurveOwnerInterface::OnCurveChanged (const TArray< FRichCurveEditInfo > & ChangedCurveEditInfos) pure virtual
Called when any of the curves have been changed.
Implemented in SRigVMGraphPinCurveFloat.
RepointCurveOwner()
virtual bool FCurveOwnerInterface::RepointCurveOwner (const FPackageReloadedEvent & InPackageReloadedEvent, FCurveOwnerInterface *& OutNewCurveOwner) const inline virtual
Called during package reload to repoint a curve interface asset.
Definition at line 76 of file CurveOwnerInterface.h.
RepointCurveOwnerAsset()
template<typename AssetType> bool FCurveOwnerInterface::RepointCurveOwnerAsset (const FPackageReloadedEvent & InPackageReloadedEvent, const AssetType * InCurveOwnerAsset, FCurveOwnerInterface *& OutNewCurveOwner) inline static protected
Default implementation of RepointCurveOwner that can be used with UObject based types that inherit FCurveOwnerInterface.
Definition at line 84 of file CurveOwnerInterface.h.
References FPackageReloadedEvent::GetRepointedObject().
The documentation for this class was generated from the following file:
CurveOwnerInterface.h