Unreal Engine 5.6 C++ API: UE::Geometry::FGroupTopology Class Reference
UE::Geometry::FGroupTopology Class Reference
Given a per-triangle integer ("group"), FGroupTopology extracts a group-level topological graph from an input Mesh.
#include "GroupTopology.h"
Data Structures
struct FCorner
FCorner is a "corner" in the group topology, IE a vertex where 3+ groups meet.
struct FGroup
FGroup is a set of connected triangles with the same GroupID.
struct FGroupBoundary
A Group is bounded by closed loops of FGroupEdge elements.
struct FGroupEdge
FGroupEdge is a sequence of group-boundary-edges where the two groups on either side of each edge are the same.
Public Member Functions
FGroupTopology ()
DYNAMICMESH_API FGroupTopology (const FDynamicMesh3 *Mesh, bool bAutoBuild)
DYNAMICMESH_API FGroupTopology (const FDynamicMesh3 *Mesh, const FDynamicMeshPolygroupAttribute *GroupLayer, bool bAutoBuild)
FGroupTopology (const FGroupTopology &)=default
virtual ~FGroupTopology ()
DYNAMICMESH_API void CollectGroupBoundaryVertices (int GroupID, TSet< int > &Vertices) const
Add all the group boundary vertices of the given GroupID to the Vertices set.
DYNAMICMESH_API void CollectGroupVertices (int GroupID, TSet< int > &Vertices) const
Add all the vertices of the given GroupID to the Vertices set.
DYNAMICMESH_API void FindCornerNbrCorners (int CornerID, TArray< int > &CornersOut) const
Add all the Corners connected to the given Corner to the EdgesOut list.
DYNAMICMESH_API void FindCornerNbrEdges (int CornerID, TArray< int > &EdgesOut) const
Add all the Edges connected to the given Corner to the EdgesOut list.
DYNAMICMESH_API void FindCornerNbrGroups (const TArray< int > &CornerIDs, TArray< int > &GroupsOut) const
Add all the groups connected to the given Corners to the GroupsOut list.
DYNAMICMESH_API void FindCornerNbrGroups (int CornerID, TArray< int > &GroupsOut) const
Add all the groups connected to the given Corner to the GroupsOut list.
DYNAMICMESH_API void FindEdgeNbrEdges (int GroupEdgeID, TArray< int > &EdgesOut) const
Add the edges connected to the given GroupEdgeID to the EdgesOut list.
DYNAMICMESH_API void FindEdgeNbrGroups (const TArray< int > &GroupEdgeIDs, TArray< int > &GroupsOut) const
Add the groups connected to all the GroupEdgeIDs to the GroupsOut list.
DYNAMICMESH_API void FindEdgeNbrGroups (int GroupEdgeID, TArray< int > &GroupsOut) const
Add the groups connected to the given GroupEdgeID to the GroupsOut list.
DYNAMICMESH_API const FGroup * FindGroupByID (int GroupID) const
DYNAMICMESH_API int FindGroupEdgeID (FMeshTriEdgeID FMeshTriEdgeID) const
DYNAMICMESH_API int FindGroupEdgeID (int MeshEdgeID) const
DYNAMICMESH_API void FindVertexNbrGroups (const TArray< int > &VertexIDs, TArray< int > &GroupsOut) const
Add all the groups connected to the given Mesh Vertices to the GroupsOut list.
DYNAMICMESH_API void FindVertexNbrGroups (int VertexID, TArray< int > &GroupsOut) const
Add all the groups connected to the given Mesh Vertex to the GroupsOut list.
DYNAMICMESH_API void ForCornerNbrEdges (int CornerID, TFunctionRef< bool(int32 EdgeID)> ReturnTrueToContinue) const
Helper that iterates over the group edges neighboring a particular corner.
template<typename FuncTakingFGroupEdgeAndInt>
void ForGroupEdges (int GroupID, const FuncTakingFGroupEdgeAndInt &EdgeFunc) const
Call EdgeFunc for each boundary edge of the given Group (no order defined).
template<typename IntIterableContainerType, typename FuncTakingFGroupEdgeAndInt>
void ForGroupSetEdges (const IntIterableContainerType &GroupIDs, const FuncTakingFGroupEdgeAndInt &EdgeFunc) const
Call EdgeFunc for each boundary edge of each of the given Groups (no order defined).
DYNAMICMESH_API int32 GetCornerIDFromVertexID (int32 VertexID) const
DYNAMICMESH_API int GetCornerVertexID (int CornerID) const
const TSet< int32 > & GetCurrentExtraCornerVids () const
DYNAMICMESH_API double GetEdgeArcLength (int32 GroupEdgeID, TArray< double > *PerVertexLengthsOut=nullptr) const
DYNAMICMESH_API FVector3d GetEdgeAveragePosition (int32 GroupEdgeID) const
DYNAMICMESH_API FVector3d GetEdgeMidpoint (int32 GroupEdgeID, double *ArcLengthOut=nullptr, TArray< double > *PerVertexLengthsOut=nullptr) const
DYNAMICMESH_API const TArray< int > & GetGroupEdgeEdges (int GroupEdgeID) const
DYNAMICMESH_API bool GetGroupEdgeTangent (int GroupEdgeID, FVector3d &TangentOut) const
Calculate tangent of group edge, as direction from start to end endpoints.
DYNAMICMESH_API const TArray< int > & GetGroupEdgeVertices (int GroupEdgeID) const
const TArray< int > & GetGroupFaces (int GroupID) const
DYNAMICMESH_API FFrame3d GetGroupFrame (int32 GroupID) const
virtual int GetGroupID (int TriangleID) const
Adjacency of Per-Triangle integers are what define the triangle groups.
DYNAMICMESH_API const TArray< int > & GetGroupNbrGroups (int GroupID) const
DYNAMICMESH_API const TArray< int > & GetGroupTriangles (int GroupID) const
const FDynamicMesh3 * GetMesh () const
DYNAMICMESH_API void GetSelectedTriangles (const FGroupTopologySelection &Selection, TArray< int32 > &Triangles) const
Get the set of selected triangles for a given GroupTopologySelection.
DYNAMICMESH_API FAxisAlignedBox3d GetSelectionBounds (const FGroupTopologySelection &Selection, TFunctionRef< FVector3d(const FVector3d &)> TransformFunc) const
DYNAMICMESH_API FFrame3d GetSelectionFrame (const FGroupTopologySelection &Selection, FFrame3d *InitialLocalFrame=nullptr) const
DYNAMICMESH_API bool IsBoundaryEdge (int32 GroupEdgeID) const
DYNAMICMESH_API bool IsGroupEdge (FMeshTriEdgeID TriEdgeID, bool bIncludeMeshBoundary=false) const
DYNAMICMESH_API bool IsIsolatedLoop (int32 GroupEdgeID) const
DYNAMICMESH_API bool IsSimpleGroupEdge (int32 GroupEdgeID) const
FGroupTopology & operator= (const FGroupTopology &)=default
virtual DYNAMICMESH_API bool RebuildTopology ()
Build the group topology graph.
virtual DYNAMICMESH_API bool RebuildTopologyWithSpecificExtraCorners (const TSet< int32 > &ExtraCornerVids)
Rebuilds the topology graph while ignoring ShouldAddExtraCornerAtVert and only determining whether an extra corner should be forced by seeing whether the vertex is in the provided set.
DYNAMICMESH_API void RetargetOnClonedMesh (const FDynamicMesh3 *Mesh)
Keeps the structures of topology in place but points the mesh pointers to a new cloned mesh.
Static Public Member Functions
static DYNAMICMESH_API bool IsEdgeAngleSharp (const FDynamicMesh3 *Mesh, int32 SharedVid, const FIndex2i &AttachedGroupEdgeEids, double DotThreshold)
Helper function for use with ShouldAddExtraCornerAtVert.
Data Fields
TArray< FCorner > Corners
List of Corners in the topology graph (ie these are the nodes/vertices of the graph)
TArray< FGroupEdge > Edges
List of Edges in the topology graph (each edge connects two corners/nodes)
TArray< FGroup > Groups
List of Groups in the topology graph (ie faces)
PRAGMA_DISABLE_DEPRECATION_WARNINGS
PRAGMA_ENABLE_DEPRECATION_WARNINGS
TFunction< bool(const FGroupTopology &GroupTopology, int32 Vid, const FIndex2i &AttachedGroupEdgeEids)> ShouldAddExtraCornerAtVert = nullptr
Optional function that will add extra corners (in addition to the ones that are always placed at junctures of three or more group edges) during RebuildTopology whenever the function returns true for a vertex that is part of a group edge.
Protected Member Functions
DYNAMICMESH_API bool GenerateBoundaryAndGroupEdges (FGroup &Group, TMap< int32, int32 > &GroupEdgeMinEidToGroupEdgeID, TBitArray<> &VertCheckedForCorner)
DYNAMICMESH_API void GetAllVertexGroups (int32 VertexID, TArray< int32 > &GroupsOut) const
FIndex2i MakeEdgeGroupsPair (int Group1, int Group2) const
FIndex2i MakeEdgeGroupsPair (int MeshEdgeID) const
virtual DYNAMICMESH_API bool ShouldVertBeCorner (int VertexID, bool *bIsExtraCornerOut=nullptr) const
Return true if the given vertex should be a corner based on the number of adjoining group edges or based on ShouldAddExtraCornerAtVert, if provided.
UE_DEPRECATED (5.1, "Group edges cannot be uniquely identified by a group pair.") int FindExistingGroupEdge(int GroupID
UE_DEPRECATED (5.1, "Use GenerateBoundaryAndGroupEdges instead.") bool ExtractGroupEdges(FGroup &Group)
Return false if we had a problem finding group boundaries.
UE_DEPRECATED (5.1, "Use MakeEdgeGroupsPair instead. The returned pair cannot uniquely identify a group edge.") inline FIndex2i MakeEdgeID(int Group1
UE_DEPRECATED (5.1, "Use MakeEdgeGroupsPair instead. The returned pair cannot uniquely identify a group edge.") inline FIndex2i MakeEdgeID(int MeshEdgeID) const
UE_DEPRECATED (5.1, "Use ShouldVertBeCorner instead.") DYNAMICMESH_API virtual bool IsCornerVertex(int VertexID) const
UE_DEPRECATED (5.1, "Use VertexIDToCornerIDMap instead.") TBitArray<> CornerVerticesFlags
Protected Attributes
int Group2 const { return MakeEdgeGroupsPair(Group1, Group2)
TSet< int32 > CurrentExtraCornerVids
TArray< int > EmptyArray
int int FirstVertexID
TArray< int > GroupIDToGroupIndexMap
const FDynamicMeshPolygroupAttribute * GroupLayer = nullptr
const FDynamicMesh3 * Mesh = nullptr
int OtherGroupID
int int int SecondVertexID { return 0
TMap< int32, int32 > VertexIDToCornerIDMap
Detailed Description
Given a per-triangle integer ("group"), FGroupTopology extracts a group-level topological graph from an input Mesh.
The graph consists of three elements: Corners: there is a corner at each vertex where 3 or more groups meet (ie 3 or more groups in one-ring) Edges: a group edge is a list of one or more connected edges that have the same pair of different groups on either side Group: a group is a set of connected faces with the same GroupID
By default, the triangle group attribute of the input Mesh is used. You can override GetGroupID to provide your own grouping.
Various query functions are provided to allow group topology to be interrogated. Note that when functions refer to "CornerID", and "GroupEdgeID", these are simply indices into the internal Corners and Edges arrays. However references to "GroupID" refer to the actual group IDs in FDynamicMesh (not an index into Groups).
Definition at line 151 of file GroupTopology.h.
Constructor & Destructor Documentation
FGroupTopology() [1/4]
UE::Geometry::FGroupTopology::FGroupTopology () inline
Definition at line 154 of file GroupTopology.h.
Referenced by FGroupTopology(), and operator=().
FGroupTopology() [2/4]
DYNAMICMESH_API UE::Geometry::FGroupTopology::FGroupTopology (const FDynamicMesh3 * Mesh, bool bAutoBuild)
References Mesh, and UE_API.
FGroupTopology() [3/4]
DYNAMICMESH_API UE::Geometry::FGroupTopology::FGroupTopology (const FDynamicMesh3 * Mesh, const FDynamicMeshPolygroupAttribute * GroupLayer, bool bAutoBuild)
References GroupLayer, Mesh, and UE_API.
FGroupTopology() [4/4]
UE::Geometry::FGroupTopology::FGroupTopology (const FGroupTopology &) default
References FGroupTopology().
~FGroupTopology()
virtual UE::Geometry::FGroupTopology::~FGroupTopology () inline virtual
Definition at line 163 of file GroupTopology.h.
Member Function Documentation
CollectGroupBoundaryVertices()
DYNAMICMESH_API void UE::Geometry::FGroupTopology::CollectGroupBoundaryVertices (int GroupID, TSet< int > & Vertices) const
Add all the group boundary vertices of the given GroupID to the Vertices set.
References UE_API, and UE::Geometry::Vertices.
CollectGroupVertices()
DYNAMICMESH_API void UE::Geometry::FGroupTopology::CollectGroupVertices (int GroupID, TSet< int > & Vertices) const
Add all the vertices of the given GroupID to the Vertices set.
References UE_API, and UE::Geometry::Vertices.
FindCornerNbrCorners()
DYNAMICMESH_API void UE::Geometry::FGroupTopology::FindCornerNbrCorners (int CornerID, TArray< int > & CornersOut) const
Add all the Corners connected to the given Corner to the EdgesOut list.
This is somewhat expensive as there is no connection from Corners to Corners, must iterate over adjacent faces/edges
References UE_API.
FindCornerNbrEdges()
DYNAMICMESH_API void UE::Geometry::FGroupTopology::FindCornerNbrEdges (int CornerID, TArray< int > & EdgesOut) const
Add all the Edges connected to the given Corner to the EdgesOut list.
This is somewhat expensive as there is no connection from Corners to Edges, must iterate over adjacent faces
References UE_API.
FindCornerNbrGroups() [1/2]
DYNAMICMESH_API void UE::Geometry::FGroupTopology::FindCornerNbrGroups (const TArray< int > & CornerIDs, TArray< int > & GroupsOut) const
Add all the groups connected to the given Corners to the GroupsOut list.
References UE_API.
FindCornerNbrGroups() [2/2]
DYNAMICMESH_API void UE::Geometry::FGroupTopology::FindCornerNbrGroups (int CornerID, TArray< int > & GroupsOut) const
Add all the groups connected to the given Corner to the GroupsOut list.
References UE_API.
FindEdgeNbrEdges()
DYNAMICMESH_API void UE::Geometry::FGroupTopology::FindEdgeNbrEdges (int GroupEdgeID, TArray< int > & EdgesOut) const
Add the edges connected to the given GroupEdgeID to the EdgesOut list.
This is somewhat expensive.
References UE_API.
FindEdgeNbrGroups() [1/2]
DYNAMICMESH_API void UE::Geometry::FGroupTopology::FindEdgeNbrGroups (const TArray< int > & GroupEdgeIDs, TArray< int > & GroupsOut) const
Add the groups connected to all the GroupEdgeIDs to the GroupsOut list.
This is not the either-side pair, but the set of groups on the one-ring of each connected corner.
References UE_API.
FindEdgeNbrGroups() [2/2]
DYNAMICMESH_API void UE::Geometry::FGroupTopology::FindEdgeNbrGroups (int GroupEdgeID, TArray< int > & GroupsOut) const
Add the groups connected to the given GroupEdgeID to the GroupsOut list.
This is not the either-side pair, but the set of groups on the one-ring of each connected corner.
References UE_API.
FindGroupByID()
DYNAMICMESH_API const FGroup * UE::Geometry::FGroupTopology::FindGroupByID (int GroupID) const
Returns
the FGroup for the given GroupID, or nullptr if not found
References UE_API.
Referenced by ForGroupEdges(), and ForGroupSetEdges().
FindGroupEdgeID() [1/2]
DYNAMICMESH_API int UE::Geometry::FGroupTopology::FindGroupEdgeID (FMeshTriEdgeID FMeshTriEdgeID) const
Returns
the ID of the FGroupEdge that contains the given Mesh Edge ID
References UE_API.
FindGroupEdgeID() [2/2]
DYNAMICMESH_API int UE::Geometry::FGroupTopology::FindGroupEdgeID (int MeshEdgeID) const
Returns
the ID of the FGroupEdge that contains the given Mesh Edge ID
References UE_API.
FindVertexNbrGroups() [1/2]
DYNAMICMESH_API void UE::Geometry::FGroupTopology::FindVertexNbrGroups (const TArray< int > & VertexIDs, TArray< int > & GroupsOut) const
Add all the groups connected to the given Mesh Vertices to the GroupsOut list.
References UE_API.
FindVertexNbrGroups() [2/2]
DYNAMICMESH_API void UE::Geometry::FGroupTopology::FindVertexNbrGroups (int VertexID, TArray< int > & GroupsOut) const
Add all the groups connected to the given Mesh Vertex to the GroupsOut list.
References UE_API.
ForCornerNbrEdges()
DYNAMICMESH_API void UE::Geometry::FGroupTopology::ForCornerNbrEdges (int CornerID, TFunctionRef< bool(int32 EdgeID)> ReturnTrueToContinue) const
Helper that iterates over the group edges neighboring a particular corner.
Parameters
ReturnTrueToContinue Function to call on all the group edges, which should return true if it wants iteration to continue, and false if it wants to exit early.
References UE_API.
ForGroupEdges()
template<typename FuncTakingFGroupEdgeAndInt> void UE::Geometry::FGroupTopology::ForGroupEdges (int GroupID, const FuncTakingFGroupEdgeAndInt & EdgeFunc) const inline
Call EdgeFunc for each boundary edge of the given Group (no order defined).
Templated so it works with both lambdas or TFunctions. Defined here to avoid dll explicit instantiation woes.
Definition at line 373 of file GroupTopology.h.
References Edges, ensure, FindGroupByID(), Group, and UE::Geometry::FGroupTopology::FGroupBoundary::GroupEdges.
ForGroupSetEdges()
template<typename IntIterableContainerType, typename FuncTakingFGroupEdgeAndInt> void UE::Geometry::FGroupTopology::ForGroupSetEdges (const IntIterableContainerType & GroupIDs, const FuncTakingFGroupEdgeAndInt & EdgeFunc) const inline
Call EdgeFunc for each boundary edge of each of the given Groups (no order defined).
Templated so that it can be used with either sets (such as selections) or lists, and works with both lambdas or TFunctions. Defined here to avoid dll explicit instantiation woes.
Definition at line 395 of file GroupTopology.h.
References TArray< InElementType, InAllocatorType >::Add(), TArray< InElementType, InAllocatorType >::Contains(), Edges, ensure, FindGroupByID(), Group, and UE::Geometry::FGroupTopology::FGroupBoundary::GroupEdges.
GenerateBoundaryAndGroupEdges()
DYNAMICMESH_API bool UE::Geometry::FGroupTopology::GenerateBoundaryAndGroupEdges (FGroup & Group, TMap< int32, int32 > & GroupEdgeMinEidToGroupEdgeID, TBitArray<> & VertCheckedForCorner) protected
References Group, and UE_API.
GetAllVertexGroups()
DYNAMICMESH_API void UE::Geometry::FGroupTopology::GetAllVertexGroups (int32 VertexID, TArray< int32 > & GroupsOut) const protected
References UE_API.
GetCornerIDFromVertexID()
DYNAMICMESH_API int32 UE::Geometry::FGroupTopology::GetCornerIDFromVertexID (int32 VertexID) const
Returns
the Group ID for a given Vertex ID, or InvalidID if vertex is not a group corner
References UE_API.
GetCornerVertexID()
DYNAMICMESH_API int UE::Geometry::FGroupTopology::GetCornerVertexID (int CornerID) const
Returns
the mesh vertex ID for the given Corner ID
References UE_API.
GetCurrentExtraCornerVids()
const TSet< int32 > & UE::Geometry::FGroupTopology::GetCurrentExtraCornerVids () const inline
Returns
Set of vertex ID's that are currently considered corners despite not originally having 3 or more attached group edges (due to the effects of ShouldAddExtraCornerAtVert or RebuildTopologyWithSpecificExtraCorners).
Definition at line 197 of file GroupTopology.h.
References CurrentExtraCornerVids.
GetEdgeArcLength()
DYNAMICMESH_API double UE::Geometry::FGroupTopology::GetEdgeArcLength (int32 GroupEdgeID, TArray< double > * PerVertexLengthsOut = nullptr) const
Returns
arc length of edge, and optionally accumulated arclength distances for each edge vertex
References UE_API.
GetEdgeAveragePosition()
DYNAMICMESH_API FVector3d UE::Geometry::FGroupTopology::GetEdgeAveragePosition (int32 GroupEdgeID) const
Returns
average position of edge (may not be on edge for curved edges)
References UE_API.
GetEdgeMidpoint()
DYNAMICMESH_API FVector3d UE::Geometry::FGroupTopology::GetEdgeMidpoint (int32 GroupEdgeID, double * ArcLengthOut = nullptr, TArray< double > * PerVertexLengthsOut = nullptr) const
Returns
arclength midpoint of edge, and optionally arclength info
References UE_API.
GetGroupEdgeEdges()
DYNAMICMESH_API const TArray< int > & UE::Geometry::FGroupTopology::GetGroupEdgeEdges (int GroupEdgeID) const
Returns
the list of edges of a FGroupEdge identified by the GroupEdgeID
References UE_API.
GetGroupEdgeTangent()
DYNAMICMESH_API bool UE::Geometry::FGroupTopology::GetGroupEdgeTangent (int GroupEdgeID, FVector3d & TangentOut) const
Calculate tangent of group edge, as direction from start to end endpoints.
Returns
false if edge is degenerate or start == end
References UE_API.
GetGroupEdgeVertices()
DYNAMICMESH_API const TArray< int > & UE::Geometry::FGroupTopology::GetGroupEdgeVertices (int GroupEdgeID) const
Returns
the list of vertices of a FGroupEdge identified by the GroupEdgeID
References UE_API.
GetGroupFaces()
const TArray< int > & UE::Geometry::FGroupTopology::GetGroupFaces (int GroupID) const inline
Returns
the list of triangles in the given GroupID, or empty list if not found
Definition at line 303 of file GroupTopology.h.
References GetGroupTriangles().
GetGroupFrame()
DYNAMICMESH_API FFrame3d UE::Geometry::FGroupTopology::GetGroupFrame (int32 GroupID) const
Returns
a 3D frame for the given group. Based on centroid of triangle centroids, so does not necessarily lie on group surface.
References UE_API.
GetGroupID()
virtual int UE::Geometry::FGroupTopology::GetGroupID (int TriangleID) const inline virtual
Adjacency of Per-Triangle integers are what define the triangle groups.
Override this function to provide an alternate group definition. Note: By convention, group IDs should not be negative
Returns
group id integer for given TriangleID
Reimplemented in UE::Geometry::FTriangleGroupTopology.
Definition at line 213 of file GroupTopology.h.
References GroupLayer, FMath::Max, and Mesh.
Referenced by UE::Geometry::FGroupTopologySelection::IsSelectedTriangle(), and MakeEdgeGroupsPair().
GetGroupNbrGroups()
DYNAMICMESH_API const TArray< int > & UE::Geometry::FGroupTopology::GetGroupNbrGroups (int GroupID) const
Returns
the list of neighbour GroupIDs for the given GroupID, or empty list if not found
References UE_API.
GetGroupTriangles()
DYNAMICMESH_API const TArray< int > & UE::Geometry::FGroupTopology::GetGroupTriangles (int GroupID) const
Returns
the list of triangles in the given GroupID, or empty list if not found
References UE_API.
Referenced by GetGroupFaces().
GetMesh()
const FDynamicMesh3 * UE::Geometry::FGroupTopology::GetMesh () const inline
Definition at line 173 of file GroupTopology.h.
References Mesh.
GetSelectedTriangles()
DYNAMICMESH_API void UE::Geometry::FGroupTopology::GetSelectedTriangles (const FGroupTopologySelection & Selection, TArray< int32 > & Triangles) const
Get the set of selected triangles for a given GroupTopologySelection.
References UE_API.
GetSelectionBounds()
DYNAMICMESH_API FAxisAlignedBox3d UE::Geometry::FGroupTopology::GetSelectionBounds (const FGroupTopologySelection & Selection, TFunctionRef< FVector3d(const FVector3d &)> TransformFunc) const
Returns
A Bounding Box for the vertices of the current selection, with TransformFunc applied
References UE_API.
GetSelectionFrame()
DYNAMICMESH_API FFrame3d UE::Geometry::FGroupTopology::GetSelectionFrame (const FGroupTopologySelection & Selection, FFrame3d * InitialLocalFrame = nullptr) const
Returns
a 3D frame for the given selection
References UE_API.
IsBoundaryEdge()
DYNAMICMESH_API bool UE::Geometry::FGroupTopology::IsBoundaryEdge (int32 GroupEdgeID) const
Returns
true if the FGroupEdge identified by the GroupEdgeID is on the mesh boundary
References UE_API.
IsEdgeAngleSharp()
DYNAMICMESH_API bool UE::Geometry::FGroupTopology::IsEdgeAngleSharp (const FDynamicMesh3 * Mesh, int32 SharedVid, const FIndex2i & AttachedGroupEdgeEids, double DotThreshold) static
Helper function for use with ShouldAddExtraCornerAtVert.
Checks that the dot product of the two mesh edge unit vectors starting from shared vertex is greater than or equal to the given threshold. Assumes that SharedVid actually is shared by the two edges, and returns false if either edge is degenerate.
Parameters
DotThreshold Threshold usually set equal to FMathd::Cos(ThresholdDegrees * FMathd::DegToRad). The parameter is not degrees just to avoid that calculation on each invocation.
References Mesh, and UE_API.
IsGroupEdge()
DYNAMICMESH_API bool UE::Geometry::FGroupTopology::IsGroupEdge (FMeshTriEdgeID TriEdgeID, bool bIncludeMeshBoundary = false) const
Returns
true if the mesh edge identified by FMeshTriEdgeID is a group boundary edge
References UE_API.
IsIsolatedLoop()
DYNAMICMESH_API bool UE::Geometry::FGroupTopology::IsIsolatedLoop (int32 GroupEdgeID) const
Returns
true if the FGroupEdge identified by the GroupEdgeID is an isolated loop (ie not connected to any other edges)
References UE_API.
IsSimpleGroupEdge()
DYNAMICMESH_API bool UE::Geometry::FGroupTopology::IsSimpleGroupEdge (int32 GroupEdgeID) const
Returns
true if group edge is a "simple" edge, meaning it only has one mesh edge
References UE_API.
MakeEdgeGroupsPair() [1/2]
FIndex2i UE::Geometry::FGroupTopology::MakeEdgeGroupsPair (int Group1, int Group2) const inline protected
Definition at line 528 of file GroupTopology.h.
References check.
MakeEdgeGroupsPair() [2/2]
FIndex2i UE::Geometry::FGroupTopology::MakeEdgeGroupsPair (int MeshEdgeID) const inline protected
Definition at line 514 of file GroupTopology.h.
References UE::Geometry::FIndex2i::A, UE::Geometry::FIndex2i::B, GetGroupID(), UE::Geometry::FDynamicMesh3::InvalidID, MakeEdgeGroupsPair(), and Mesh.
Referenced by MakeEdgeGroupsPair(), and UE_DEPRECATED().
operator=()
FGroupTopology & UE::Geometry::FGroupTopology::operator= (const FGroupTopology &) default
References FGroupTopology().
RebuildTopology()
virtual DYNAMICMESH_API bool UE::Geometry::FGroupTopology::RebuildTopology () virtual
Build the group topology graph.
Returns
true on success, false if there was an error
Reimplemented in UE::Geometry::FTriangleGroupTopology.
References UE_API.
RebuildTopologyWithSpecificExtraCorners()
virtual DYNAMICMESH_API bool UE::Geometry::FGroupTopology::RebuildTopologyWithSpecificExtraCorners (const TSet< int32 > & ExtraCornerVids) virtual
Rebuilds the topology graph while ignoring ShouldAddExtraCornerAtVert and only determining whether an extra corner should be forced by seeing whether the vertex is in the provided set.
This is used to rebuild the topology with a particular group of extra corners during client undo/redo operations where the behavior of ShouldAddExtraCornerAtVert may have changed in the interim.
References UE_API.
RetargetOnClonedMesh()
DYNAMICMESH_API void UE::Geometry::FGroupTopology::RetargetOnClonedMesh (const FDynamicMesh3 * Mesh)
Keeps the structures of topology in place but points the mesh pointers to a new cloned mesh.
If the given mesh is not cloned, the topology will no longer be consistent.
References Mesh, and UE_API.
ShouldVertBeCorner()
virtual DYNAMICMESH_API bool UE::Geometry::FGroupTopology::ShouldVertBeCorner (int VertexID, bool * bIsExtraCornerOut = nullptr) const protected virtual
Return true if the given vertex should be a corner based on the number of adjoining group edges or based on ShouldAddExtraCornerAtVert, if provided.
Parameters
bIsExtraCornerOut Set to true if the vertex didn't have 3 or more group adjoining edges, but was forced to be a corner by ShouldAddExtraCornerAtVert.
References const, ShouldVertBeCorner(), and UE_API.
Referenced by ShouldVertBeCorner().
UE_DEPRECATED() [1/6]
UE::Geometry::FGroupTopology::UE_DEPRECATED (5. 1, "Group edges cannot be uniquely identified by a group pair.") protected
UE_DEPRECATED() [2/6]
UE::Geometry::FGroupTopology::UE_DEPRECATED (5. 1, "Use GenerateBoundaryAndGroupEdges instead.") & inline protected
Return false if we had a problem finding group boundaries.
Definition at line 494 of file GroupTopology.h.
References Group, and UE_DEPRECATED().
UE_DEPRECATED() [3/6]
UE::Geometry::FGroupTopology::UE_DEPRECATED (5. 1, "Use MakeEdgeGroupsPair instead. The returned pair cannot uniquely identify a group edge.") protected
UE_DEPRECATED() [4/6]
UE::Geometry::FGroupTopology::UE_DEPRECATED (5. 1, "Use MakeEdgeGroupsPair instead. The returned pair cannot uniquely identify a group edge.") const inline protected
Definition at line 500 of file GroupTopology.h.
References MakeEdgeGroupsPair().
UE_DEPRECATED() [5/6]
UE::Geometry::FGroupTopology::UE_DEPRECATED (5. 1, "Use ShouldVertBeCorner instead.") const protected
Returns
true if given mesh vertex should be a Corner vertex. This looks at the actual mesh- it doesn't use the topology structures.
References const, UE_API, and UE_DEPRECATED().
UE_DEPRECATED() [6/6]
UE::Geometry::FGroupTopology::UE_DEPRECATED (5. 1, "Use VertexIDToCornerIDMap instead.") protected
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
Field Documentation
const
int Group2 UE::Geometry::FGroupTopology::const { return MakeEdgeGroupsPair(Group1, Group2) protected
Definition at line 503 of file GroupTopology.h.
Referenced by ShouldVertBeCorner(), and UE_DEPRECATED().
Corners
TArray<FCorner> UE::Geometry::FGroupTopology::Corners
List of Corners in the topology graph (ie these are the nodes/vertices of the graph)
Definition at line 231 of file GroupTopology.h.
CurrentExtraCornerVids
TSet<int32> UE::Geometry::FGroupTopology::CurrentExtraCornerVids protected
Definition at line 475 of file GroupTopology.h.
Referenced by GetCurrentExtraCornerVids().
Edges
TArray<FGroupEdge> UE::Geometry::FGroupTopology::Edges
List of Edges in the topology graph (each edge connects two corners/nodes)
Definition at line 290 of file GroupTopology.h.
Referenced by ForGroupEdges(), and ForGroupSetEdges().
EmptyArray
TArray<int> UE::Geometry::FGroupTopology::EmptyArray protected
Definition at line 472 of file GroupTopology.h.
FirstVertexID
int int UE::Geometry::FGroupTopology::FirstVertexID protected
Definition at line 509 of file GroupTopology.h.
GroupIDToGroupIndexMap
TArray<int> UE::Geometry::FGroupTopology::GroupIDToGroupIndexMap protected
Definition at line 467 of file GroupTopology.h.
GroupLayer
const FDynamicMeshPolygroupAttribute* UE::Geometry::FGroupTopology::GroupLayer = nullptr protected
Definition at line 465 of file GroupTopology.h.
Referenced by FGroupTopology(), and GetGroupID().
Groups
TArray<FGroup> UE::Geometry::FGroupTopology::Groups
List of Groups in the topology graph (ie faces)
Definition at line 259 of file GroupTopology.h.
Mesh
const FDynamicMesh3* UE::Geometry::FGroupTopology::Mesh = nullptr protected
Definition at line 464 of file GroupTopology.h.
Referenced by FGroupTopology(), FGroupTopology(), UE::Geometry::FTriangleGroupTopology::FTriangleGroupTopology(), FUVGroupTopology::FUVGroupTopology(), GetGroupID(), GetMesh(), IsEdgeAngleSharp(), MakeEdgeGroupsPair(), and RetargetOnClonedMesh().
OtherGroupID
int UE::Geometry::FGroupTopology::OtherGroupID protected
Definition at line 509 of file GroupTopology.h.
PRAGMA_DISABLE_DEPRECATION_WARNINGS
UE::Geometry::FGroupTopology::PRAGMA_DISABLE_DEPRECATION_WARNINGS
Definition at line 160 of file GroupTopology.h.
PRAGMA_ENABLE_DEPRECATION_WARNINGS
UE::Geometry::FGroupTopology::PRAGMA_ENABLE_DEPRECATION_WARNINGS
Definition at line 164 of file GroupTopology.h.
SecondVertexID
int int int UE::Geometry::FGroupTopology::SecondVertexID { return 0 protected
Definition at line 509 of file GroupTopology.h.
ShouldAddExtraCornerAtVert
TFunction<bool(const FGroupTopology& GroupTopology, int32 Vid, const FIndex2i& AttachedGroupEdgeEids)> UE::Geometry::FGroupTopology::ShouldAddExtraCornerAtVert = nullptr
Optional function that will add extra corners (in addition to the ones that are always placed at junctures of three or more group edges) during RebuildTopology whenever the function returns true for a vertex that is part of a group edge.
For instance, this allows corners to be placed at sharp group edge bends even if the given vertex doesn't connect 3 or more group edges.
Definition at line 191 of file GroupTopology.h.
VertexIDToCornerIDMap
TMap<int32, int32> UE::Geometry::FGroupTopology::VertexIDToCornerIDMap protected
Definition at line 473 of file GroupTopology.h.
The documentation for this class was generated from the following file:
GroupTopology.h