Unreal Engine 5.6 C++ API: Nanite::FResources Struct Reference
Nanite::FResources Struct Reference
#include "NaniteResources.h"
Data Structures
struct FDDCRebuildState
Public Member Functions
void DropBulkData ()
void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize) const
bool HasBuildFromDDCError () const
bool HasStreamingData () const
void InitResources (const UObject *Owner)
bool IsRootPage (uint32 PageIndex) const
bool RebuildBulkDataFromCacheAsync (const UObject *Owner, bool &bFailed)
Requests (or polls) an async operation that rebuilds the streaming bulk data from the cache.
bool ReleaseResources ()
void Serialize (FArchive &Ar, UObject *Owner, bool bCooked)
void SetHasBuildFromDDCError (bool bHasError)
UE_DEPRECATED (5.1, "Use RebuildBulkDataFromCacheAsync instead.") 1 void RebuildBulkDataFromDDC(const UObject *Owner)
Data Fields
uint32 AssemblyTransformOffset = MAX_uint32
TArray< FMatrix3x4 > AssemblyTransforms
FIoHash DDCKeyHash
FIoHash DDCRawHash
TArray< FPackedHierarchyNode > HierarchyNodes
uint32 HierarchyOffset = MAX_uint32
TArray< uint32 > HierarchyRootOffsets
TArray< uint16 > ImposterAtlas
int32 ImposterIndex = INDEX_NONE
FBoxSphereBounds3f MeshBounds = FBoxSphereBounds3f(ForceInit)
int32 NormalPrecision = 0
uint32 NumClusters = 0
uint32 NumHierarchyDwords = 0
uint32 NumHierarchyNodes = 0
uint32 NumInputTriangles = 0
uint32 NumInputVertices = 0
uint32 NumResidentClusters = 0
uint32 NumRootPages = 0
TArray< uint32 > PageDependencies
TArray< FPageStreamingState > PageStreamingStates
uint32 PersistentHash = NANITE_INVALID_PERSISTENT_HASH
int32 PositionPrecision = 0
uint32 ResourceFlags = 0
FString ResourceName
TArray< uint8 > RootData
int32 RootPageIndex = INDEX_NONE
uint32 RuntimeResourceID = MAX_uint32
FByteBulkData StreamablePages
int32 TangentPrecision = 0
Private Types
enum class EDDCRebuildState : uint8 {
Initial , InitialAfterFailed , Pending , Succeeded ,
Failed
}
Private Member Functions
void BeginRebuildBulkDataFromCache (const UObject *Owner)
Begins an async rebuild of the bulk data from the cache.
void EndRebuildBulkDataFromCache ()
Ends an async rebuild of the bulk data from the cache.
void SerializeInternal (FArchive &Ar, UObject *Owner, bool bCooked)
Static Private Member Functions
static bool IsInitialState (EDDCRebuildState State)
Private Attributes
FDDCRebuildState DDCRebuildState
TDontCopy< TPimplPtr< UE::DerivedData::FRequestOwner > > DDCRequestOwner
Detailed Description
Definition at line 481 of file NaniteResources.h.
Member Enumeration Documentation
EDDCRebuildState
enum class Nanite::FResources::EDDCRebuildState : uint8 strong private
Enumerator
Initial
InitialAfterFailed
Pending
Succeeded
Failed
Definition at line 520 of file NaniteResources.h.
Member Function Documentation
BeginRebuildBulkDataFromCache()
void Nanite::FResources::BeginRebuildBulkDataFromCache (const UObject * Owner) private
Begins an async rebuild of the bulk data from the cache.
Must be paired with EndRebuildBulkDataFromCache.
References Owner.
DropBulkData()
void Nanite::FResources::DropBulkData ()
EndRebuildBulkDataFromCache()
void Nanite::FResources::EndRebuildBulkDataFromCache () private
Ends an async rebuild of the bulk data from the cache.
May block if poll has not returned true.
GetResourceSizeEx()
void Nanite::FResources::GetResourceSizeEx (FResourceSizeEx & CumulativeResourceSize) const
HasBuildFromDDCError()
bool Nanite::FResources::HasBuildFromDDCError () const
References HasBuildFromDDCError().
Referenced by HasBuildFromDDCError().
HasStreamingData()
bool Nanite::FResources::HasStreamingData () const
InitResources()
void Nanite::FResources::InitResources (const UObject * Owner)
References Owner.
IsInitialState()
bool Nanite::FResources::IsInitialState (EDDCRebuildState State) inline static private
Definition at line 528 of file NaniteResources.h.
References Initial, InitialAfterFailed, and State.
Referenced by Nanite::FResources::FDDCRebuildState::operator=().
IsRootPage()
bool Nanite::FResources::IsRootPage (uint32 PageIndex) const inline
Definition at line 572 of file NaniteResources.h.
References NumRootPages.
RebuildBulkDataFromCacheAsync()
bool Nanite::FResources::RebuildBulkDataFromCacheAsync (const UObject * Owner, bool & bFailed)
Requests (or polls) an async operation that rebuilds the streaming bulk data from the cache.
If a rebuild is already in progress, the call will just poll the pending operation. If true is returned, the operation is complete and it is safe to access the streaming data. If false is returned, the operation has not yet completed. The operation can fail, which is indicated by the value of bFailed.
References Owner, and RebuildBulkDataFromCacheAsync().
Referenced by RebuildBulkDataFromCacheAsync().
ReleaseResources()
bool Nanite::FResources::ReleaseResources ()
Serialize()
void Nanite::FResources::Serialize (FArchive & Ar, UObject * Owner, bool bCooked)
References Ar, and Owner.
SerializeInternal()
void Nanite::FResources::SerializeInternal (FArchive & Ar, UObject * Owner, bool bCooked) private
References Ar, and Owner.
SetHasBuildFromDDCError()
void Nanite::FResources::SetHasBuildFromDDCError (bool bHasError)
References SetHasBuildFromDDCError().
Referenced by SetHasBuildFromDDCError().
UE_DEPRECATED()
Nanite::FResources::UE_DEPRECATED (5. 1, "Use RebuildBulkDataFromCacheAsync instead.") const
References Owner.
Field Documentation
AssemblyTransformOffset
uint32 Nanite::FResources::AssemblyTransformOffset = MAX_uint32
Definition at line 505 of file NaniteResources.h.
AssemblyTransforms
TArray< FMatrix3x4 > Nanite::FResources::AssemblyTransforms
Definition at line 491 of file NaniteResources.h.
DDCKeyHash
FIoHash Nanite::FResources::DDCKeyHash
Definition at line 515 of file NaniteResources.h.
DDCRawHash
FIoHash Nanite::FResources::DDCRawHash
Definition at line 516 of file NaniteResources.h.
DDCRebuildState
FDDCRebuildState Nanite::FResources::DDCRebuildState private
Definition at line 542 of file NaniteResources.h.
DDCRequestOwner
TDontCopy<TPimplPtr<UE::DerivedData::FRequestOwner> > Nanite::FResources::DDCRequestOwner private
Definition at line 518 of file NaniteResources.h.
HierarchyNodes
TArray< FPackedHierarchyNode > Nanite::FResources::HierarchyNodes
Definition at line 487 of file NaniteResources.h.
HierarchyOffset
uint32 Nanite::FResources::HierarchyOffset = MAX_uint32
Definition at line 504 of file NaniteResources.h.
HierarchyRootOffsets
TArray< uint32 > Nanite::FResources::HierarchyRootOffsets
Definition at line 488 of file NaniteResources.h.
ImposterAtlas
TArray< uint16 > Nanite::FResources::ImposterAtlas
Definition at line 486 of file NaniteResources.h.
ImposterIndex
int32 Nanite::FResources::ImposterIndex = INDEX_NONE
Definition at line 507 of file NaniteResources.h.
MeshBounds
FBoxSphereBounds3f Nanite::FResources::MeshBounds = FBoxSphereBounds3f(ForceInit)
Definition at line 492 of file NaniteResources.h.
NormalPrecision
int32 Nanite::FResources::NormalPrecision = 0
Definition at line 495 of file NaniteResources.h.
NumClusters
uint32 Nanite::FResources::NumClusters = 0
Definition at line 499 of file NaniteResources.h.
NumHierarchyDwords
uint32 Nanite::FResources::NumHierarchyDwords = 0
Definition at line 509 of file NaniteResources.h.
NumHierarchyNodes
uint32 Nanite::FResources::NumHierarchyNodes = 0
Definition at line 508 of file NaniteResources.h.
NumInputTriangles
uint32 Nanite::FResources::NumInputTriangles = 0
Definition at line 497 of file NaniteResources.h.
NumInputVertices
uint32 Nanite::FResources::NumInputVertices = 0
Definition at line 498 of file NaniteResources.h.
NumResidentClusters
uint32 Nanite::FResources::NumResidentClusters = 0
Definition at line 510 of file NaniteResources.h.
NumRootPages
uint32 Nanite::FResources::NumRootPages = 0
Definition at line 493 of file NaniteResources.h.
Referenced by IsRootPage().
PageDependencies
TArray< uint32 > Nanite::FResources::PageDependencies
Definition at line 490 of file NaniteResources.h.
PageStreamingStates
TArray< FPageStreamingState > Nanite::FResources::PageStreamingStates
Definition at line 489 of file NaniteResources.h.
Referenced by FSkinnedMeshComponentHelper::HasValidNaniteData(), and Nanite::FNaniteResourcesHelper::HasValidNaniteData().
PersistentHash
uint32 Nanite::FResources::PersistentHash = NANITE_INVALID_PERSISTENT_HASH
Definition at line 511 of file NaniteResources.h.
PositionPrecision
int32 Nanite::FResources::PositionPrecision = 0
Definition at line 494 of file NaniteResources.h.
ResourceFlags
uint32 Nanite::FResources::ResourceFlags = 0
Definition at line 500 of file NaniteResources.h.
ResourceName
FString Nanite::FResources::ResourceName
Definition at line 514 of file NaniteResources.h.
RootData
TArray< uint8 > Nanite::FResources::RootData
Definition at line 484 of file NaniteResources.h.
RootPageIndex
int32 Nanite::FResources::RootPageIndex = INDEX_NONE
Definition at line 506 of file NaniteResources.h.
RuntimeResourceID
uint32 Nanite::FResources::RuntimeResourceID = MAX_uint32
Definition at line 503 of file NaniteResources.h.
StreamablePages
FByteBulkData Nanite::FResources::StreamablePages
Definition at line 485 of file NaniteResources.h.
TangentPrecision
int32 Nanite::FResources::TangentPrecision = 0
Definition at line 496 of file NaniteResources.h.
The documentation for this struct was generated from the following file:
NaniteResources.h