Unreal Engine 5.6 C++ API: Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator > Class Template Reference
Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator > Class Template Reference
#include "RobinHoodHashTable.h"
Data Structures
class FConstIteratorType
struct FData
class FIteratorType
Public Member Functions
FIteratorType begin ()
FConstIteratorType begin () const
bool ContainsElementId (FHashElementId Id) const
void Empty ()
FIteratorType end ()
FConstIteratorType end () const
FindValueType Find (const KeyType &Key)
FindValueTypeConst Find (const KeyType &Key) const
FindValueType FindByHash (const FHashType HashValue, const KeyType &Key)
const FindValueType FindByHash (const FHashType HashValue, const KeyType &Key) const
FHashElementId FindId (const KeyType &Key) const
FHashElementId FindIdByHash (const FHashType HashValue, const KeyType &ComparableKey) const
SizeType GetAllocatedSize () const
ElementType & GetByElementId (FHashElementId Id)
const ElementType & GetByElementId (FHashElementId Id) const
IndexType GetMaxIndex () const
int32 Num () const
bool Remove (const KeyType &Key)
bool RemoveByElementId (FHashElementId Id)
bool RemoveByHash (const FHashType HashValue, const KeyType &ComparableKey)
void Reserve (SizeType ReserveNum)
Static Public Member Functions
static FHashType ComputeHash (const KeyType &Key)
Protected Types
using ElementType = typename KeyValueType::ElementType
using FindValueType = typename KeyValueType::FindValueType
using FindValueTypeConst = typename KeyValueType::FindValueTypeConst
using IndexType = uint32
using InlineOneAllocatorType = TInlineAllocator<1, HashMapAllocator>
using KeyValueType = RobinHoodHashTable_Private::TKeyValue<KeyType, ValueType>
using SizeType = SIZE_T
Protected Member Functions
TRobinHoodHashTable ()
TRobinHoodHashTable (const TRobinHoodHashTable &Other)
TRobinHoodHashTable (TRobinHoodHashTable &&Other)
template<typename DeducedKeyType, typename DeducedValueType>
FindValueType FindOrAdd (DeducedKeyType &&Key, DeducedValueType &&Val, bool &bIsAlreadyInMap)
template<typename DeducedKeyType, typename DeducedValueType>
FHashElementId FindOrAddId (DeducedKeyType &&Key, DeducedValueType &&Val, bool &bIsAlreadyInMap)
template<typename DeducedKeyType, typename DeducedValueType>
FHashElementId FindOrAddIdByHash (FHashType HashValue, DeducedKeyType &&Key, DeducedValueType &&Val, bool &bIsAlreadyInMap)
void InsertIntoTable (IndexType Index, FHashType Hash)
IndexType ModTableSize (IndexType HashValue) const
TRobinHoodHashTable & operator= (const TRobinHoodHashTable &Other)
TRobinHoodHashTable & operator= (TRobinHoodHashTable &&Other)
template<typename DeducedKeyType, typename DeducedValueType>
FindValueType Update (DeducedKeyType &&Key, DeducedValueType &&Val, bool &bIsAlreadyInMap)
template<typename DeducedKeyType, typename DeducedValueType>
FHashElementId UpdateId (DeducedKeyType &&Key, DeducedValueType &&Val, bool &bIsAlreadyInMap)
template<typename DeducedKeyType, typename DeducedValueType>
FHashElementId UpdateIdByHash (FHashType HashValue, DeducedKeyType &&Key, DeducedValueType &&Val, bool &bIsAlreadyInMap)
Static Protected Attributes
static constexpr const IndexType InvalidIndex = ~IndexType(0)
static constexpr const IndexType LoadFactorDivisor = 3
static constexpr const IndexType LoadFactorQuotient = 5
Private Member Functions
template<bool UpdateValue, typename DeducedKeyType, typename DeducedValueType>
FHashElementId FindOrUpdateIdByHashInternal (FHashType HashValue, DeducedKeyType &&Key, DeducedValueType &&Val, bool &bIsAlreadyInMap)
Private Attributes
TArray< FHashType, InlineOneAllocatorType > HashData
TArray< IndexType, InlineOneAllocatorType > IndexData
FData KeyValueData
IndexType MaximumDistance = 0
IndexType SizePow2Minus1 = 0
Detailed Description
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator>
class Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >
Definition at line 315 of file RobinHoodHashTable.h.
Member Typedef Documentation
ElementType
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> using Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::ElementType = typename KeyValueType::ElementType protected
Definition at line 322 of file RobinHoodHashTable.h.
FindValueType
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> using Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FindValueType = typename KeyValueType::FindValueType protected
Definition at line 320 of file RobinHoodHashTable.h.
FindValueTypeConst
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> using Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FindValueTypeConst = typename KeyValueType::FindValueTypeConst protected
Definition at line 321 of file RobinHoodHashTable.h.
IndexType
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> using Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::IndexType = uint32 protected
Definition at line 323 of file RobinHoodHashTable.h.
InlineOneAllocatorType
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> using Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::InlineOneAllocatorType = TInlineAllocator<1, HashMapAllocator> protected
Definition at line 318 of file RobinHoodHashTable.h.
KeyValueType
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> using Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::KeyValueType = RobinHoodHashTable_Private::TKeyValue<KeyType, ValueType> protected
Definition at line 319 of file RobinHoodHashTable.h.
SizeType
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> using Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::SizeType = SIZE_T protected
Definition at line 324 of file RobinHoodHashTable.h.
Constructor & Destructor Documentation
TRobinHoodHashTable() [1/3]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::TRobinHoodHashTable () inline protected
Definition at line 642 of file RobinHoodHashTable.h.
References HashData, and IndexData.
Referenced by TRobinHoodHashTable(), TRobinHoodHashTable(), operator=(), and operator=().
TRobinHoodHashTable() [2/3]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::TRobinHoodHashTable (const TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator > & Other) inline protected
Definition at line 648 of file RobinHoodHashTable.h.
References TRobinHoodHashTable(), HashData, IndexData, KeyValueData, MaximumDistance, Other, and SizePow2Minus1.
TRobinHoodHashTable() [3/3]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::TRobinHoodHashTable (TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator > && Other) inline protected
Definition at line 689 of file RobinHoodHashTable.h.
References TRobinHoodHashTable(), HashData, IndexData, KeyValueData, MaximumDistance, MoveTemp(), Other, and SizePow2Minus1.
Member Function Documentation
begin() [1/2]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FIteratorType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::begin () inline
Definition at line 774 of file RobinHoodHashTable.h.
References KeyValueData.
begin() [2/2]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FConstIteratorType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::begin () const inline
Definition at line 832 of file RobinHoodHashTable.h.
References KeyValueData.
ComputeHash()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FHashType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::ComputeHash (const KeyType & Key) inline static
Definition at line 719 of file RobinHoodHashTable.h.
References Key.
Referenced by FindId(), FindIdByHash(), FindOrAddId(), FindOrUpdateIdByHashInternal(), Remove(), RemoveByHash(), and UpdateId().
ContainsElementId()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> bool Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::ContainsElementId (FHashElementId Id) const inline
Definition at line 867 of file RobinHoodHashTable.h.
References Experimental::FHashElementId::GetIndex(), and KeyValueData.
Empty()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> void Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::Empty () inline
Definition at line 1059 of file RobinHoodHashTable.h.
References CHECK_CONCURRENT_ACCESS, HashData, IndexData, KeyValueData, MaximumDistance, and SizePow2Minus1.
end() [1/2]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FIteratorType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::end () inline
Definition at line 779 of file RobinHoodHashTable.h.
References KeyValueData.
end() [2/2]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FConstIteratorType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::end () const inline
Definition at line 837 of file RobinHoodHashTable.h.
References KeyValueData.
Find() [1/2]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FindValueType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::Find (const KeyType & Key) inline
Definition at line 918 of file RobinHoodHashTable.h.
References FindId(), Experimental::FHashElementId::GetIndex(), Experimental::FHashElementId::IsValid(), Key, and KeyValueData.
Find() [2/2]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FindValueTypeConst Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::Find (const KeyType & Key) const inline
Definition at line 940 of file RobinHoodHashTable.h.
References FindId(), Experimental::FHashElementId::GetIndex(), Experimental::FHashElementId::IsValid(), Key, and KeyValueData.
FindByHash() [1/2]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FindValueType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FindByHash (const FHashType HashValue, const KeyType & Key) inline
Definition at line 907 of file RobinHoodHashTable.h.
References FindIdByHash(), Experimental::FHashElementId::GetIndex(), Experimental::FHashElementId::IsValid(), Key, and KeyValueData.
FindByHash() [2/2]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> const FindValueType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FindByHash (const FHashType HashValue, const KeyType & Key) const inline
Definition at line 929 of file RobinHoodHashTable.h.
References FindIdByHash(), Experimental::FHashElementId::GetIndex(), Experimental::FHashElementId::IsValid(), Key, and KeyValueData.
FindId()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FHashElementId Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FindId (const KeyType & Key) const inline
Definition at line 901 of file RobinHoodHashTable.h.
References ComputeHash(), FindIdByHash(), and Key.
Referenced by Find(), and Find().
FindIdByHash()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FHashElementId Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FindIdByHash (const FHashType HashValue, const KeyType & ComparableKey) const inline
Definition at line 872 of file RobinHoodHashTable.h.
References Experimental::FHashType::AsUInt(), CHECK_CONCURRENT_ACCESS, checkSlow, ComputeHash(), HashData, IndexData, KeyValueData, MaximumDistance, and ModTableSize().
Referenced by FindByHash(), FindByHash(), and FindId().
FindOrAdd()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> template<typename DeducedKeyType, typename DeducedValueType> FindValueType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FindOrAdd (DeducedKeyType && Key, DeducedValueType && Val, bool & bIsAlreadyInMap) inline protected
Definition at line 616 of file RobinHoodHashTable.h.
References FindOrAddId(), Forward(), Experimental::FHashElementId::GetIndex(), Key, and KeyValueData.
FindOrAddId()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> template<typename DeducedKeyType, typename DeducedValueType> FHashElementId Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FindOrAddId (DeducedKeyType && Key, DeducedValueType && Val, bool & bIsAlreadyInMap) inline protected
Definition at line 609 of file RobinHoodHashTable.h.
References ComputeHash(), FindOrAddIdByHash(), Forward(), and Key.
Referenced by FindOrAdd().
FindOrAddIdByHash()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> template<typename DeducedKeyType, typename DeducedValueType> FHashElementId Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FindOrAddIdByHash (FHashType HashValue, DeducedKeyType && Key, DeducedValueType && Val, bool & bIsAlreadyInMap) inline protected
Definition at line 603 of file RobinHoodHashTable.h.
References FindOrUpdateIdByHashInternal(), Forward(), and Key.
Referenced by FindOrAddId().
FindOrUpdateIdByHashInternal()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> template<bool UpdateValue, typename DeducedKeyType, typename DeducedValueType> FHashElementId Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FindOrUpdateIdByHashInternal (FHashType HashValue, DeducedKeyType && Key, DeducedValueType && Val, bool & bIsAlreadyInMap) inline private
Definition at line 542 of file RobinHoodHashTable.h.
References Experimental::FHashType::AsUInt(), CHECK_CONCURRENT_ACCESS, checkSlow, ComputeHash(), Forward(), HashData, IndexData, InsertIntoTable(), Key, KeyValueData, LoadFactorDivisor, LoadFactorQuotient, MaximumDistance, ModTableSize(), MoveTemp(), and SizePow2Minus1.
Referenced by FindOrAddIdByHash(), and UpdateIdByHash().
GetAllocatedSize()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> SizeType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::GetAllocatedSize () const inline
Definition at line 842 of file RobinHoodHashTable.h.
References HashData, IndexData, and KeyValueData.
GetByElementId() [1/2]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> ElementType & Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::GetByElementId (FHashElementId Id) inline
Definition at line 857 of file RobinHoodHashTable.h.
References Experimental::FHashElementId::GetIndex(), and KeyValueData.
GetByElementId() [2/2]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> const ElementType & Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::GetByElementId (FHashElementId Id) const inline
Definition at line 862 of file RobinHoodHashTable.h.
References Experimental::FHashElementId::GetIndex(), and KeyValueData.
GetMaxIndex()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> IndexType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::GetMaxIndex () const inline
Definition at line 852 of file RobinHoodHashTable.h.
References KeyValueData.
InsertIntoTable()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> void Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::InsertIntoTable (IndexType Index, FHashType Hash) inline protected
Definition at line 495 of file RobinHoodHashTable.h.
References checkSlow, Hash, HashData, IndexData, MaximumDistance, and ModTableSize().
Referenced by FindOrUpdateIdByHashInternal(), RemoveByElementId(), RemoveByHash(), and Reserve().
ModTableSize()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> IndexType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::ModTableSize (IndexType HashValue) const inline protected
Definition at line 490 of file RobinHoodHashTable.h.
References SizePow2Minus1.
Referenced by FindIdByHash(), FindOrUpdateIdByHashInternal(), InsertIntoTable(), RemoveByElementId(), and RemoveByHash().
Num()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> int32 Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::Num () const inline
Definition at line 847 of file RobinHoodHashTable.h.
References KeyValueData.
operator=() [1/2]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> TRobinHoodHashTable & Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::operator= (const TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator > & Other) inline protected
Definition at line 666 of file RobinHoodHashTable.h.
References TRobinHoodHashTable(), HashData, IndexData, KeyValueData, MaximumDistance, Other, and SizePow2Minus1.
operator=() [2/2]
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> TRobinHoodHashTable & Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::operator= (TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator > && Other) inline protected
Definition at line 701 of file RobinHoodHashTable.h.
References TRobinHoodHashTable(), HashData, IndexData, KeyValueData, MaximumDistance, MoveTemp(), Other, and SizePow2Minus1.
Remove()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> bool Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::Remove (const KeyType & Key) inline
Definition at line 1003 of file RobinHoodHashTable.h.
References ComputeHash(), Key, and RemoveByHash().
RemoveByElementId()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> bool Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::RemoveByElementId (FHashElementId Id) inline
Definition at line 1009 of file RobinHoodHashTable.h.
References Experimental::FHashType::AsUInt(), CHECK_CONCURRENT_ACCESS, checkSlow, Experimental::FHashElementId::GetIndex(), HashData, IndexData, InsertIntoTable(), KeyValueData, LoadFactorDivisor, LoadFactorQuotient, MaximumDistance, ModTableSize(), MoveTemp(), and SizePow2Minus1.
RemoveByHash()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> bool Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::RemoveByHash (const FHashType HashValue, const KeyType & ComparableKey) inline
Definition at line 951 of file RobinHoodHashTable.h.
References Experimental::FHashType::AsUInt(), CHECK_CONCURRENT_ACCESS, checkSlow, ComputeHash(), HashData, IndexData, InsertIntoTable(), KeyValueData, LoadFactorDivisor, LoadFactorQuotient, MaximumDistance, ModTableSize(), MoveTemp(), and SizePow2Minus1.
Referenced by Remove().
Reserve()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> void Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::Reserve (SizeType ReserveNum) inline
Definition at line 1076 of file RobinHoodHashTable.h.
References CHECK_CONCURRENT_ACCESS, HashData, IndexData, InsertIntoTable(), KeyValueData, LoadFactorDivisor, LoadFactorQuotient, MaximumDistance, MoveTemp(), and SizePow2Minus1.
Update()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> template<typename DeducedKeyType, typename DeducedValueType> FindValueType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::Update (DeducedKeyType && Key, DeducedValueType && Val, bool & bIsAlreadyInMap) inline protected
Definition at line 636 of file RobinHoodHashTable.h.
References Forward(), Experimental::FHashElementId::GetIndex(), Key, KeyValueData, and UpdateId().
UpdateId()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> template<typename DeducedKeyType, typename DeducedValueType> FHashElementId Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::UpdateId (DeducedKeyType && Key, DeducedValueType && Val, bool & bIsAlreadyInMap) inline protected
Definition at line 629 of file RobinHoodHashTable.h.
References ComputeHash(), Forward(), Key, and UpdateIdByHash().
Referenced by Update().
UpdateIdByHash()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> template<typename DeducedKeyType, typename DeducedValueType> FHashElementId Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::UpdateIdByHash (FHashType HashValue, DeducedKeyType && Key, DeducedValueType && Val, bool & bIsAlreadyInMap) inline protected
Definition at line 623 of file RobinHoodHashTable.h.
References FindOrUpdateIdByHashInternal(), Forward(), and Key.
Referenced by UpdateId().
Field Documentation
HashData
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> TArray<FHashType, InlineOneAllocatorType> Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::HashData private
Definition at line 1121 of file RobinHoodHashTable.h.
Referenced by TRobinHoodHashTable(), TRobinHoodHashTable(), TRobinHoodHashTable(), Empty(), FindIdByHash(), FindOrUpdateIdByHashInternal(), GetAllocatedSize(), InsertIntoTable(), operator=(), operator=(), RemoveByElementId(), RemoveByHash(), and Reserve().
IndexData
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> TArray<IndexType, InlineOneAllocatorType> Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::IndexData private
Definition at line 1120 of file RobinHoodHashTable.h.
Referenced by TRobinHoodHashTable(), TRobinHoodHashTable(), TRobinHoodHashTable(), Empty(), FindIdByHash(), FindOrUpdateIdByHashInternal(), GetAllocatedSize(), InsertIntoTable(), operator=(), operator=(), RemoveByElementId(), RemoveByHash(), and Reserve().
InvalidIndex
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> const IndexType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::InvalidIndex = ~IndexType(0) static constexpr protected
Definition at line 328 of file RobinHoodHashTable.h.
Referenced by Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::Allocate(), Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::Next(), and Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FData::Start().
KeyValueData
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FData Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::KeyValueData private
Definition at line 1118 of file RobinHoodHashTable.h.
Referenced by TRobinHoodHashTable(), TRobinHoodHashTable(), begin(), begin(), ContainsElementId(), Empty(), end(), end(), Find(), Find(), FindByHash(), FindByHash(), FindIdByHash(), FindOrAdd(), FindOrUpdateIdByHashInternal(), GetAllocatedSize(), GetByElementId(), GetByElementId(), GetMaxIndex(), Num(), operator=(), operator=(), RemoveByElementId(), RemoveByHash(), Reserve(), and Update().
LoadFactorDivisor
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> const IndexType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::LoadFactorDivisor = 3 static constexpr protected
Definition at line 326 of file RobinHoodHashTable.h.
Referenced by FindOrUpdateIdByHashInternal(), RemoveByElementId(), RemoveByHash(), and Reserve().
LoadFactorQuotient
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> const IndexType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::LoadFactorQuotient = 5 static constexpr protected
Definition at line 327 of file RobinHoodHashTable.h.
Referenced by FindOrUpdateIdByHashInternal(), RemoveByElementId(), RemoveByHash(), and Reserve().
MaximumDistance
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> IndexType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::MaximumDistance = 0 private
Definition at line 1124 of file RobinHoodHashTable.h.
Referenced by TRobinHoodHashTable(), TRobinHoodHashTable(), Empty(), FindIdByHash(), FindOrUpdateIdByHashInternal(), InsertIntoTable(), operator=(), operator=(), RemoveByElementId(), RemoveByHash(), and Reserve().
SizePow2Minus1
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> IndexType Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::SizePow2Minus1 = 0 private
Definition at line 1123 of file RobinHoodHashTable.h.
Referenced by TRobinHoodHashTable(), TRobinHoodHashTable(), Empty(), FindOrUpdateIdByHashInternal(), ModTableSize(), operator=(), operator=(), RemoveByElementId(), RemoveByHash(), and Reserve().
The documentation for this class was generated from the following file:
RobinHoodHashTable.h