Unreal Engine 5.6 C++ API: TraceServices::IRegionProvider Class Reference
TraceServices::IRegionProvider Class Reference abstract
#include "Regions.h"
Public Member Functions
virtual ~IRegionProvider () override=default
virtual void EnumerateTimelinesByCategory (TFunctionRef< void(const IRegionTimeline &, const TCHAR *)> Callback) const =0
Enumerates all timelines, this includes the uncategorized timeline with uncategorized regions and individual timelines for each Category.
virtual const IRegionTimeline & GetDefaultTimeline () const =0
virtual uint64 GetRegionCount () const =0
virtual const IRegionTimeline * GetTimelineForCategory (const TCHAR *Category) const =0
virtual const TCHAR * GetUncategorizedRegionCategoryName () const =0
virtual uint64 GetUpdateCounter () const =0
UE_DEPRECATED (5.6, "Use GetDefaultTimeline().EnumerateLanes() or EnumerateTimelinesByCategory() to access timelines instead.") virtual void EnumerateLanes(TFunctionRef< void(const FRegionLane &
Will call Callback(Lane, Depth) for each lane in order.
UE_DEPRECATED (5.6, "Use GetDefaultTimeline().EnumerateRegions() or EnumerateTimelinesByCategory() to access timelines instead.") virtual bool EnumerateRegions(double IntervalStart
Enumerates all regions that overlap a certain time interval.
UE_DEPRECATED (5.6, "Use GetDefaultTimeline().GetLane() or EnumerateTimelinesByCategory() to access timelines instead.") virtual const FRegionLane *GetLane(int32 Index) const =0
Direct access to a certain lane at a given index/depth of the default timeline.
UE_DEPRECATED (5.6, "Use GetDefaultTimeline().GetLaneCount() or EnumerateTimelinesByCategory() to access timelines instead.") virtual int32 GetLaneCount() const =0
Public Member Functions inherited from TraceServices::IProvider
virtual ~IProvider ()=default
virtual void BeginRead () const
virtual void EndRead () const
virtual void ReadAccessCheck () const
Data Fields
double TFunctionRef< bool(const FTimeRegion &)> Callback const = 0
const int32 Callback const = 0
double IntervalEnd
Detailed Description
Definition at line 83 of file Regions.h.
Constructor & Destructor Documentation
~IRegionProvider()
virtual TraceServices::IRegionProvider::~IRegionProvider () override virtual default
Member Function Documentation
EnumerateTimelinesByCategory()
virtual void TraceServices::IRegionProvider::EnumerateTimelinesByCategory (TFunctionRef< void(const IRegionTimeline &, const TCHAR *)> Callback) const pure virtual
Enumerates all timelines, this includes the uncategorized timeline with uncategorized regions and individual timelines for each Category.
Parameters
Callback a callback called for each timeline. Second parameter contains Category or nullptr for the uncategorized timeline.
GetDefaultTimeline()
virtual const IRegionTimeline & TraceServices::IRegionProvider::GetDefaultTimeline () const pure virtual
Returns
the default timeline containing all regions without filtering
GetRegionCount()
virtual uint64 TraceServices::IRegionProvider::GetRegionCount () const pure virtual
Returns
the amount of currently known regions (including open-ended ones)
GetTimelineForCategory()
virtual const IRegionTimeline * TraceServices::IRegionProvider::GetTimelineForCategory (const TCHAR * Category) const pure virtual
Returns
the timeline for a given Category or the timeline with uncategorized regions if Category is nullptr. Returns nullptr if the category was invalid/not found
References Category.
GetUncategorizedRegionCategoryName()
virtual const TCHAR * TraceServices::IRegionProvider::GetUncategorizedRegionCategoryName () const pure virtual
Returns
returns the string used to store regions with no explicit category set ("__Uncategorized__")
GetUpdateCounter()
virtual uint64 TraceServices::IRegionProvider::GetUpdateCounter () const pure virtual
Returns
a monotonically increasing counter that is updated each time new data is added to the provider. This can be used to detect when to update any (UI-)state dependent on the provider during analysis.
References const, and GetUpdateCounter().
Referenced by GetUpdateCounter().
UE_DEPRECATED() [1/4]
TraceServices::IRegionProvider::UE_DEPRECATED (5. 6, "Use GetDefaultTimeline().EnumerateLanes() or EnumerateTimelinesByCategory() to access timelines instead.") const &
Will call Callback(Lane, Depth) for each lane in order.
References UE_DEPRECATED().
UE_DEPRECATED() [2/4]
TraceServices::IRegionProvider::UE_DEPRECATED (5. 6, "Use GetDefaultTimeline().EnumerateRegions() or EnumerateTimelinesByCategory() to access timelines instead.")
Enumerates all regions that overlap a certain time interval.
Will enumerate by depth but does not expose lanes.
Parameters
Callback a callback called for each region. Return false to abort iteration.
Returns
true if the enumeration finished, false if it was aborted by the callback returning false
References UE_DEPRECATED().
UE_DEPRECATED() [3/4]
TraceServices::IRegionProvider::UE_DEPRECATED (5. 6, "Use GetDefaultTimeline().GetLane() or EnumerateTimelinesByCategory() to access timelines instead.") const pure virtual
Direct access to a certain lane at a given index/depth of the default timeline.
The pointer is valid only in the current read scope.
Returns
a pointer to the lane at the specified depth index or nullptr if Index > GetLaneCount()-1
References const, and UE_DEPRECATED().
UE_DEPRECATED() [4/4]
TraceServices::IRegionProvider::UE_DEPRECATED (5. 6, "Use GetDefaultTimeline().GetLaneCount() or EnumerateTimelinesByCategory() to access timelines instead.") const pure virtual
Returns
the number of lanes of the default timeline
References const.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
Field Documentation
const [1/2]
double TFunctionRef<bool(const FTimeRegion&)> Callback TraceServices::IRegionProvider::const = 0
Definition at line 136 of file Regions.h.
Referenced by GetUpdateCounter(), UE_DEPRECATED(), and UE_DEPRECATED().
const [2/2]
const int32 Callback TraceServices::IRegionProvider::const = 0
Definition at line 143 of file Regions.h.
IntervalEnd
double TraceServices::IRegionProvider::IntervalEnd
Definition at line 136 of file Regions.h.
The documentation for this class was generated from the following file:
Regions.h