Unreal Engine 5.6 C++ API: FRigVMTreeLoadPackageForNodeTask Class Reference
FRigVMTreeLoadPackageForNodeTask Class Reference
The Load Package For Node Task will load a package related to a node given the node's path.
#include "RigVMTreeToolkitTask.h"
Public Types
typedef FRigVMTreeTask Super
Public Types inherited from FRigVMTreeTask
typedef FRigVMTreeElement Super
Public Member Functions
FRigVMTreeLoadPackageForNodeTask (const TSharedRef< FRigVMTreeNode > &InNode)
virtual bool Execute (const TSharedRef< FRigVMTreePhase > &InPhase) override
virtual FName GetType () const override
virtual bool IsOfType (const FName &InType) const override
virtual bool RequiresRefresh () const override
TSharedPtr< FRigVMTreeLoadPackageForNodeTask > ToSharedPtr () const
TSharedRef< FRigVMTreeLoadPackageForNodeTask > ToSharedRef () const
Public Member Functions inherited from FRigVMTreeTask
virtual TArray< FString > GetAffectedNodes () const
virtual URigVMBlueprint * GetBlueprint (const TSharedRef< FRigVMTreePhase > &InPhase) const
bool IsUndoEnabled () const
virtual bool RequiresUndo () const
void SetEnableUndo (bool bEnabled)
TSharedPtr< FRigVMTreeTask > ToSharedPtr () const
TSharedRef< FRigVMTreeTask > ToSharedRef () const
Public Member Functions inherited from FRigVMTreeElement
virtual ~FRigVMTreeElement ()
virtual void Initialize ()
template<typename T>
bool IsA () const
Public Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
TSharedRef< FRigVMTreeElement, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FRigVMTreeElement, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
template<typename... Types>
static TSharedRef< FRigVMTreeLoadPackageForNodeTask > Create (Types... Args)
Static Public Member Functions inherited from FRigVMTreeTask
template<typename... Types>
static TSharedRef< FRigVMTreeTask > Create (Types... Args)
Static Public Attributes
static const FLazyName Type = FLazyName(TEXT("FRigVMTreeLoadPackageForNodeTask"))
Static Public Attributes inherited from FRigVMTreeTask
static const FLazyName Type = FLazyName(TEXT("FRigVMTreeTask"))
Static Public Attributes inherited from FRigVMTreeElement
static const FLazyName Type = FLazyName(TEXT("FRigVMTreeElement"))
Private Attributes
FAssetData AssetData
Friends
template<typename T>
TSharedPtr< T > Cast (const TSharedRef< FRigVMTreeLoadPackageForNodeTask > &InElement)
template<typename T>
const TSharedRef< T > & CastChecked (const TSharedRef< FRigVMTreeLoadPackageForNodeTask > &InElement)
Additional Inherited Members
Protected Member Functions inherited from FRigVMTreeElement
FRigVMTreeElement ()
Protected Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
The Load Package For Node Task will load a package related to a node given the node's path.
Definition at line 64 of file RigVMTreeToolkitTask.h.
Member Typedef Documentation
Super
typedef FRigVMTreeTask FRigVMTreeLoadPackageForNodeTask::Super
Definition at line 67 of file RigVMTreeToolkitTask.h.
Constructor & Destructor Documentation
FRigVMTreeLoadPackageForNodeTask()
FRigVMTreeLoadPackageForNodeTask::FRigVMTreeLoadPackageForNodeTask (const TSharedRef< FRigVMTreeNode > & InNode)
References FRigVMTreeLoadPackageForNodeTask().
Referenced by FRigVMTreeLoadPackageForNodeTask(), and Cast.
Member Function Documentation
Create()
template<typename... Types> TSharedRef< FRigVMTreeLoadPackageForNodeTask > FRigVMTreeLoadPackageForNodeTask::Create (Types... Args) inline static
Definition at line 67 of file RigVMTreeToolkitTask.h.
Execute()
virtual bool FRigVMTreeLoadPackageForNodeTask::Execute (const TSharedRef< FRigVMTreePhase > & InPhase) override virtual
Reimplemented from FRigVMTreeTask.
References Execute().
Referenced by Execute().
GetType()
virtual FName FRigVMTreeLoadPackageForNodeTask::GetType () const inline override virtual
Reimplemented from FRigVMTreeTask.
Definition at line 67 of file RigVMTreeToolkitTask.h.
IsOfType()
virtual bool FRigVMTreeLoadPackageForNodeTask::IsOfType (const FName & InType) const inline override virtual
Reimplemented from FRigVMTreeTask.
Definition at line 67 of file RigVMTreeToolkitTask.h.
RequiresRefresh()
virtual bool FRigVMTreeLoadPackageForNodeTask::RequiresRefresh () const inline override virtual
Reimplemented from FRigVMTreeTask.
Definition at line 73 of file RigVMTreeToolkitTask.h.
References RequiresRefresh().
Referenced by RequiresRefresh().
ToSharedPtr()
TSharedPtr< FRigVMTreeLoadPackageForNodeTask > FRigVMTreeLoadPackageForNodeTask::ToSharedPtr () const inline
Definition at line 67 of file RigVMTreeToolkitTask.h.
ToSharedRef()
TSharedRef< FRigVMTreeLoadPackageForNodeTask > FRigVMTreeLoadPackageForNodeTask::ToSharedRef () const inline
Definition at line 67 of file RigVMTreeToolkitTask.h.
Friends And Related Symbol Documentation
Cast
template<typename T> TSharedPtr< T > Cast (const TSharedRef< FRigVMTreeLoadPackageForNodeTask > & InElement) friend
Definition at line 67 of file RigVMTreeToolkitTask.h.
References FRigVMTreeLoadPackageForNodeTask().
CastChecked
template<typename T> const TSharedRef< T > & CastChecked (const TSharedRef< FRigVMTreeLoadPackageForNodeTask > & InElement) friend
Definition at line 67 of file RigVMTreeToolkitTask.h.
Field Documentation
AssetData
FAssetData FRigVMTreeLoadPackageForNodeTask::AssetData private
Definition at line 79 of file RigVMTreeToolkitTask.h.
Type
const FLazyName FRigVMTreeLoadPackageForNodeTask::Type = FLazyName(TEXT("FRigVMTreeLoadPackageForNodeTask")) inline static
Definition at line 67 of file RigVMTreeToolkitTask.h.
The documentation for this class was generated from the following file:
RigVMTreeToolkitTask.h