Unreal Engine 5.6 C++ API: FBaseCompactPose< InAllocator > Struct Template Reference
FBaseCompactPose< InAllocator > Struct Template Reference
#include "BonePose.h"
Public Types
typedef InAllocator Allocator
typedef FCompactPoseBoneIndex BoneIndexType
typedef FBasePose< FCompactPoseBoneIndex, Allocator >::template FRangedForReverseSupport< FBaseCompactPose, FCompactPoseBoneIndexReverseIterator > RangedForBoneIndexBwd
typedef FBasePose< FCompactPoseBoneIndex, Allocator >::template FRangedForSupport< FBaseCompactPose, FCompactPoseBoneIndexIterator > RangedForBoneIndexFwd
Public Member Functions
FBaseCompactPose ()
bool ContainsNaN () const
void CopyAndAssignBoneContainer (FBoneContainer &NewBoneContainer)
void CopyBonesFrom (const FBaseCompactPose< Allocator > &SrcPose)
template<typename OtherAllocator>
void CopyBonesFrom (const FBaseCompactPose< OtherAllocator > &SrcPose)
template<typename OtherAllocator>
void CopyBonesFrom (const TArray< FTransform, OtherAllocator > &SrcPoseBones)
template<typename OtherAllocator>
void CopyBonesTo (TArray< FTransform, OtherAllocator > &DestPoseBones) const
void Empty ()
FORCEINLINE RangedForBoneIndexFwd ForEachBoneIndex () const
FORCEINLINE RangedForBoneIndexBwd ForEachBoneIndexReverse () const
FBoneContainer & GetBoneContainer ()
const FBoneContainer & GetBoneContainer () const
BoneIndexType GetParentBoneIndex (const BoneIndexType &BoneIndex) const
const FTransform & GetRefPose (const BoneIndexType &BoneIndex) const
void InitFrom (const FBaseCompactPose &SrcPose)
void InitFrom (FBaseCompactPose &&SrcPose)
bool IsNormalized () const
bool IsValid () const
FORCEINLINE FCompactPoseBoneIndexIterator MakeBeginIter () const
FORCEINLINE FCompactPoseBoneIndexReverseIterator MakeBeginIterReverse () const
FORCEINLINE FCompactPoseBoneIndexIterator MakeEndIter () const
FORCEINLINE FCompactPoseBoneIndexReverseIterator MakeEndIterReverse () const
void MoveBonesFrom (FBaseCompactPose< Allocator > &SrcPose)
void MoveBonesFrom (TArray< FTransform, Allocator > &&InTransforms)
void MoveBonesTo (TArray< FTransform, Allocator > &InTransforms)
void NormalizeRotations ()
void ResetToAdditiveIdentity ()
void ResetToRefPose ()
void ResetToRefPose (const FBoneContainer &RequiredBones)
void SetBoneContainer (const FBoneContainer *InBoneContainer)
Public Member Functions inherited from FBasePose< FCompactPoseBoneIndex, InAllocator >
const TArray< FTransform, InAllocator > & GetBones () const
FORCEINLINE TArrayView< FTransform > GetMutableBones ()
FORCEINLINE int32 GetNumBones () const
FORCEINLINE void InitBones (int32 NumBones)
FORCEINLINE bool IsValidIndex (const FCompactPoseBoneIndex &BoneIndex) const
TArray< FTransform, InAllocator > && MoveBones ()
FORCEINLINE FTransform & operator[] (const FCompactPoseBoneIndex &BoneIndex)
Protected Attributes
const FBoneContainer * BoneContainer
Protected Attributes inherited from FBasePose< FCompactPoseBoneIndex, InAllocator >
TArray< FTransform, InAllocator > Bones
Detailed Description
template<typename InAllocator>
struct FBaseCompactPose< InAllocator >
Definition at line 103 of file BonePose.h.
Member Typedef Documentation
Allocator
template<typename InAllocator> typedef InAllocator FBaseCompactPose< InAllocator >::Allocator
Definition at line 112 of file BonePose.h.
BoneIndexType
template<typename InAllocator> typedef FCompactPoseBoneIndex FBaseCompactPose< InAllocator >::BoneIndexType
Definition at line 111 of file BonePose.h.
RangedForBoneIndexBwd
template<typename InAllocator> typedef FBasePose<FCompactPoseBoneIndex,Allocator>::template FRangedForReverseSupport<FBaseCompactPose, FCompactPoseBoneIndexReverseIterator> FBaseCompactPose< InAllocator >::RangedForBoneIndexBwd
Definition at line 116 of file BonePose.h.
RangedForBoneIndexFwd
template<typename InAllocator> typedef FBasePose<FCompactPoseBoneIndex,Allocator>::template FRangedForSupport<FBaseCompactPose, FCompactPoseBoneIndexIterator> FBaseCompactPose< InAllocator >::RangedForBoneIndexFwd
Definition at line 115 of file BonePose.h.
Constructor & Destructor Documentation
FBaseCompactPose()
template<typename InAllocator> FBaseCompactPose< InAllocator >::FBaseCompactPose () inline
Definition at line 107 of file BonePose.h.
References BoneContainer.
Referenced by CopyBonesFrom(), CopyBonesFrom(), InitFrom(), InitFrom(), and MoveBonesFrom().
Member Function Documentation
ContainsNaN()
template<typename InAllocator> bool FBaseCompactPose< InAllocator >::ContainsNaN () const inline
Definition at line 300 of file BonePose.h.
References FBasePose< FCompactPoseBoneIndex, InAllocator >::Bones.
CopyAndAssignBoneContainer()
template<typename InAllocator> void FBaseCompactPose< InAllocator >::CopyAndAssignBoneContainer (FBoneContainer & NewBoneContainer) inline
Definition at line 156 of file BonePose.h.
References BoneContainer.
CopyBonesFrom() [1/3]
template<typename InAllocator> void FBaseCompactPose< InAllocator >::CopyBonesFrom (const FBaseCompactPose< Allocator > & SrcPose) inline
Definition at line 183 of file BonePose.h.
References FBaseCompactPose(), BoneContainer, FBasePose< FCompactPoseBoneIndex, InAllocator >::Bones, GetBoneContainer(), and FBasePose< BoneIndexType, InAllocator >::GetBones().
CopyBonesFrom() [2/3]
template<typename InAllocator> template<typename OtherAllocator> void FBaseCompactPose< InAllocator >::CopyBonesFrom (const FBaseCompactPose< OtherAllocator > & SrcPose) inline
Definition at line 177 of file BonePose.h.
References FBaseCompactPose(), BoneContainer, FBasePose< FCompactPoseBoneIndex, InAllocator >::Bones, GetBoneContainer(), and FBasePose< BoneIndexType, InAllocator >::GetBones().
CopyBonesFrom() [3/3]
template<typename InAllocator> template<typename OtherAllocator> void FBaseCompactPose< InAllocator >::CopyBonesFrom (const TArray< FTransform, OtherAllocator > & SrcPoseBones) inline
Definition at line 203 of file BonePose.h.
References FBasePose< FCompactPoseBoneIndex, InAllocator >::Bones, and TArray< InElementType, InAllocatorType >::Num().
CopyBonesTo()
template<typename InAllocator> template<typename OtherAllocator> void FBaseCompactPose< InAllocator >::CopyBonesTo (TArray< FTransform, OtherAllocator > & DestPoseBones) const inline
Definition at line 215 of file BonePose.h.
References FBasePose< FCompactPoseBoneIndex, InAllocator >::Bones.
Empty()
template<typename InAllocator> void FBaseCompactPose< InAllocator >::Empty () inline
Definition at line 235 of file BonePose.h.
References BoneContainer, and FBasePose< FCompactPoseBoneIndex, InAllocator >::Bones.
ForEachBoneIndex()
template<typename InAllocator> FORCEINLINE RangedForBoneIndexFwd FBaseCompactPose< InAllocator >::ForEachBoneIndex () const inline
Definition at line 118 of file BonePose.h.
References FORCEINLINE.
Referenced by ResetToRefPose().
ForEachBoneIndexReverse()
template<typename InAllocator> FORCEINLINE RangedForBoneIndexBwd FBaseCompactPose< InAllocator >::ForEachBoneIndexReverse () const inline
Definition at line 123 of file BonePose.h.
References FORCEINLINE.
GetBoneContainer() [1/2]
template<typename InAllocator> FBoneContainer & FBaseCompactPose< InAllocator >::GetBoneContainer () inline
Definition at line 143 of file BonePose.h.
References BoneContainer, and checkSlow.
GetBoneContainer() [2/2]
template<typename InAllocator> const FBoneContainer & FBaseCompactPose< InAllocator >::GetBoneContainer () const inline
Definition at line 137 of file BonePose.h.
References BoneContainer, and checkSlow.
Referenced by CopyBonesFrom(), CopyBonesFrom(), GetParentBoneIndex(), GetRefPose(), MoveBonesFrom(), ResetToRefPose(), and ResetToRefPose().
GetParentBoneIndex()
template<typename InAllocator> BoneIndexType FBaseCompactPose< InAllocator >::GetParentBoneIndex (const BoneIndexType & BoneIndex) const inline
Definition at line 329 of file BonePose.h.
References GetBoneContainer(), and FBoneContainer::GetParentBoneIndex().
Referenced by FCSPose< PoseType >::ConvertComponentPosesToLocalPoses(), and FCSPose< PoseType >::ConvertComponentPosesToLocalPosesSafe().
GetRefPose()
template<typename InAllocator> const FTransform & FBaseCompactPose< InAllocator >::GetRefPose (const BoneIndexType & BoneIndex) const inline
Definition at line 335 of file BonePose.h.
References GetBoneContainer(), and FBoneContainer::GetRefPoseTransform().
InitFrom() [1/2]
template<typename InAllocator> void FBaseCompactPose< InAllocator >::InitFrom (const FBaseCompactPose< InAllocator > & SrcPose) inline
Definition at line 162 of file BonePose.h.
References FBaseCompactPose(), BoneContainer, FBasePose< BoneIndexType, InAllocator >::Bones, FBasePose< FCompactPoseBoneIndex, InAllocator >::Bones, and SetBoneContainer().
InitFrom() [2/2]
template<typename InAllocator> void FBaseCompactPose< InAllocator >::InitFrom (FBaseCompactPose< InAllocator > && SrcPose) inline
Definition at line 168 of file BonePose.h.
References FBaseCompactPose(), FBasePose< FCompactPoseBoneIndex, InAllocator >::Bones, MoveTemp(), and SetBoneContainer().
IsNormalized()
template<typename InAllocator> bool FBaseCompactPose< InAllocator >::IsNormalized () const inline
Definition at line 286 of file BonePose.h.
References FBasePose< FCompactPoseBoneIndex, InAllocator >::Bones.
IsValid()
template<typename InAllocator> bool FBaseCompactPose< InAllocator >::IsValid () const inline
Definition at line 323 of file BonePose.h.
References BoneContainer.
MakeBeginIter()
template<typename InAllocator> FORCEINLINE FCompactPoseBoneIndexIterator FBaseCompactPose< InAllocator >::MakeBeginIter () const inline
Definition at line 128 of file BonePose.h.
References FORCEINLINE.
MakeBeginIterReverse()
template<typename InAllocator> FORCEINLINE FCompactPoseBoneIndexReverseIterator FBaseCompactPose< InAllocator >::MakeBeginIterReverse () const inline
Definition at line 132 of file BonePose.h.
References FORCEINLINE, and FBasePose< FCompactPoseBoneIndex, InAllocator >::GetNumBones().
MakeEndIter()
template<typename InAllocator> FORCEINLINE FCompactPoseBoneIndexIterator FBaseCompactPose< InAllocator >::MakeEndIter () const inline
Definition at line 130 of file BonePose.h.
References FORCEINLINE, and FBasePose< FCompactPoseBoneIndex, InAllocator >::GetNumBones().
MakeEndIterReverse()
template<typename InAllocator> FORCEINLINE FCompactPoseBoneIndexReverseIterator FBaseCompactPose< InAllocator >::MakeEndIterReverse () const inline
Definition at line 134 of file BonePose.h.
References FORCEINLINE.
MoveBonesFrom() [1/2]
template<typename InAllocator> void FBaseCompactPose< InAllocator >::MoveBonesFrom (FBaseCompactPose< Allocator > & SrcPose) inline
Definition at line 192 of file BonePose.h.
References FBaseCompactPose(), BoneContainer, FBasePose< FCompactPoseBoneIndex, InAllocator >::Bones, GetBoneContainer(), and FBasePose< BoneIndexType, InAllocator >::MoveBones().
MoveBonesFrom() [2/2]
template<typename InAllocator> void FBaseCompactPose< InAllocator >::MoveBonesFrom (TArray< FTransform, Allocator > && InTransforms) inline
Definition at line 224 of file BonePose.h.
References FBasePose< FCompactPoseBoneIndex, InAllocator >::Bones, and MoveTemp().
MoveBonesTo()
template<typename InAllocator> void FBaseCompactPose< InAllocator >::MoveBonesTo (TArray< FTransform, Allocator > & InTransforms) inline
Definition at line 230 of file BonePose.h.
References FBasePose< FCompactPoseBoneIndex, InAllocator >::Bones, and MoveTemp().
NormalizeRotations()
template<typename InAllocator> void FBaseCompactPose< InAllocator >::NormalizeRotations () inline
Definition at line 315 of file BonePose.h.
References FBasePose< FCompactPoseBoneIndex, InAllocator >::Bones.
ResetToAdditiveIdentity()
template<typename InAllocator> void FBaseCompactPose< InAllocator >::ResetToAdditiveIdentity () inline
Definition at line 277 of file BonePose.h.
References FBasePose< FCompactPoseBoneIndex, InAllocator >::Bones.
ResetToRefPose() [1/2]
template<typename InAllocator> void FBaseCompactPose< InAllocator >::ResetToRefPose () inline
Definition at line 242 of file BonePose.h.
References GetBoneContainer(), and ResetToRefPose().
Referenced by ResetToRefPose().
ResetToRefPose() [2/2]
template<typename InAllocator> void FBaseCompactPose< InAllocator >::ResetToRefPose (const FBoneContainer & RequiredBones) inline
Definition at line 248 of file BonePose.h.
References BoneContainer, FBasePose< FCompactPoseBoneIndex, InAllocator >::Bones, checkSlow, FBoneContainer::FillWithCompactRefPose(), ForEachBoneIndex(), GetBoneContainer(), FBoneContainer::GetDisableRetargeting(), FBoneContainer::GetSkeletalMeshAsset(), FBoneContainer::GetSkeletonAsset(), FBoneContainer::GetSkeletonIndex(), INDEX_NONE, and FBoneContainer::IsValid().
SetBoneContainer()
template<typename InAllocator> void FBaseCompactPose< InAllocator >::SetBoneContainer (const FBoneContainer * InBoneContainer) inline
Definition at line 149 of file BonePose.h.
References BoneContainer, check, FBasePose< FCompactPoseBoneIndex, InAllocator >::InitBones(), and FBoneContainer::IsValid().
Referenced by InitFrom(), and InitFrom().
Field Documentation
BoneContainer
template<typename InAllocator> const FBoneContainer* FBaseCompactPose< InAllocator >::BoneContainer protected
Definition at line 343 of file BonePose.h.
Referenced by FBaseCompactPose(), CopyAndAssignBoneContainer(), CopyBonesFrom(), CopyBonesFrom(), Empty(), GetBoneContainer(), GetBoneContainer(), InitFrom(), IsValid(), MoveBonesFrom(), ResetToRefPose(), and SetBoneContainer().
The documentation for this struct was generated from the following file:
BonePose.h