Unreal Engine 5.6 C++ API: FMovieSceneDynamicBindingUtils Struct Reference
FMovieSceneDynamicBindingUtils Struct Reference
A utility class for managing dynamic binding endpoints.
#include "MovieSceneDynamicBindingUtils.h"
Public Types
using FSharedPlaybackState = UE::MovieScene::FSharedPlaybackState
Static Public Member Functions
static void EnsureBlueprintExtensionCreated (UMovieSceneSequence *MovieSceneSequence, UBlueprint *Blueprint)
Ensures that the dynamic binding blueprint extension has been added to the given sequence's director blueprint.
static void GatherDynamicBindings (UMovieScene *InMovieScene, TArray< FMovieSceneDynamicBinding * > &OutDynamicBindings)
Utility function for gathering all dynamic bindings in a sequence into a container.
template<typename Callback>
static void IterateDynamicBindings (UMovieScene *InMovieScene, Callback &&InCallback)
Utility function for iterating all dynamic bindings in a sequence.
static void SetEndpoint (UMovieScene *MovieScene, FMovieSceneDynamicBinding *DynamicBinding, UK2Node *NewEndpoint)
Set an endpoint on the given dynamic binding.
Detailed Description
A utility class for managing dynamic binding endpoints.
Definition at line 21 of file MovieSceneDynamicBindingUtils.h.
Member Typedef Documentation
FSharedPlaybackState
using FMovieSceneDynamicBindingUtils::FSharedPlaybackState = UE::MovieScene::FSharedPlaybackState
Definition at line 23 of file MovieSceneDynamicBindingUtils.h.
Member Function Documentation
EnsureBlueprintExtensionCreated()
void FMovieSceneDynamicBindingUtils::EnsureBlueprintExtensionCreated (UMovieSceneSequence * MovieSceneSequence, UBlueprint * Blueprint) static
Ensures that the dynamic binding blueprint extension has been added to the given sequence's director blueprint.
GatherDynamicBindings()
void FMovieSceneDynamicBindingUtils::GatherDynamicBindings (UMovieScene * InMovieScene, TArray< FMovieSceneDynamicBinding * > & OutDynamicBindings) inline static
Utility function for gathering all dynamic bindings in a sequence into a container.
Definition at line 49 of file MovieSceneDynamicBindingUtils.h.
References TArray< InElementType, InAllocatorType >::Add(), Item, and IterateDynamicBindings().
IterateDynamicBindings()
template<typename Callback> void FMovieSceneDynamicBindingUtils::IterateDynamicBindings (UMovieScene * InMovieScene, Callback && InCallback) inline static
Utility function for iterating all dynamic bindings in a sequence.
Definition at line 39 of file MovieSceneDynamicBindingUtils.h.
Referenced by GatherDynamicBindings().
SetEndpoint()
void FMovieSceneDynamicBindingUtils::SetEndpoint (UMovieScene * MovieScene, FMovieSceneDynamicBinding * DynamicBinding, UK2Node * NewEndpoint) static
Set an endpoint on the given dynamic binding.
The documentation for this struct was generated from the following file:
MovieSceneDynamicBindingUtils.h