Unreal Engine 5.6 C++ API: UGameplayAbilitiesDeveloperSettings Class Reference
UGameplayAbilitiesDeveloperSettings Class Reference
#include "GameplayAbilitiesDeveloperSettings.h"
Private Member Functions
virtual bool CanEditChange (const FProperty *InProperty) const override
virtual void OverrideConfigSection (FString &InOutSectionName) override
GENERATED_BODY() public UPROPERTY () bool bUseDebugTargetFromHud
UPROPERTY () bool PredictTargetGameplayEffects
Set to true if you want clients to try to predict gameplay effects done to targets.
UPROPERTY () bool ReplicateActivationOwnedTags
Set to true if you want tags granted to owners from ability activations to be replicated.
UPROPERTY () int32 MinimalReplicationTagCountBits
How many bits to use for "number of tags" in FMinimalReplicationTagCountMap::NetSerialize.
UPROPERTY ()) bool bAllowGameplayModEvaluationChannels
Whether the game should allow the usage of gameplay mod evaluation channels or not.
UPROPERTY ()) EGameplayModEvaluationChannel DefaultGameplayModEvaluationChannel
The default mod evaluation channel for the game.
UPROPERTY ()) FGameplayTag ActivateFailCanActivateAbilityTag
TryActive failed due to GameplayAbility's CanActivateAbility function (Blueprint or Native)
UPROPERTY ()) FGameplayTag ActivateFailCooldownTag
TryActivate failed due to being on cooldown.
UPROPERTY ()) FGameplayTag ActivateFailCostTag
TryActivate failed due to not being able to spend costs.
UPROPERTY ()) FGameplayTag ActivateFailNetworkingTag
Failed to activate due to invalid networking settings, this is designer error.
UPROPERTY ()) FGameplayTag ActivateFailTagsBlockedTag
TryActivate failed due to being blocked by other abilities.
UPROPERTY ()) FGameplayTag ActivateFailTagsMissingTag
TryActivate failed due to missing required tags.
UPROPERTY ()) FName GameplayModEvaluationChannelAliases[10]
Game-specified named aliases for gameplay mod evaluation channels; Only those with valid aliases are eligible to be used in a game (except Channel0, which is always valid)
UPROPERTY ()) FSoftClassPath GlobalGameplayCueManagerClass
Class reference to gameplay cue manager.
UPROPERTY ()) FSoftObjectPath GameplayTagResponseTableName
The class to instantiate as the GameplayTagResponseTable.
UPROPERTY ()) FSoftObjectPath GlobalAttributeMetaDataTableName
Holds information about the valid attributes' min and max values and stacking rules.
UPROPERTY ()) FSoftObjectPath GlobalCurveTableName
Name of global curve table to use as the default for scalable floats, etc.
UPROPERTY ()) FSoftObjectPath GlobalGameplayCueManagerName
Class reference to gameplay cue manager.
UPROPERTY ()) TArray< FSoftObjectPath > GlobalAttributeSetDefaultsTableNames
Array of curve table names to use for default values for attribute sets, keyed off of Name/Levels.
UPROPERTY ()) TArray< FString > GameplayCueNotifyPaths
Look in these paths for GameplayCueNotifies.
Detailed Description
Definition at line 30 of file GameplayAbilitiesDeveloperSettings.h.
Member Function Documentation
CanEditChange()
virtual bool UGameplayAbilitiesDeveloperSettings::CanEditChange (const FProperty * InProperty) const override private virtual
OverrideConfigSection()
virtual void UGameplayAbilitiesDeveloperSettings::OverrideConfigSection (FString & InOutSectionName) inline override private virtual
Definition at line 125 of file GameplayAbilitiesDeveloperSettings.h.
References TEXT.
UPROPERTY() [1/20]
GENERATED_BODY() public UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
References Category.
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [2/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
Set to true if you want clients to try to predict gameplay effects done to targets.
If false it will only predict self effects
References Category, and UPROPERTY().
UPROPERTY() [3/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
Set to true if you want tags granted to owners from ability activations to be replicated.
If false, ActivationOwnedTags are only applied locally. This should only be disabled for legacy game code that depends on non-replication of ActivationOwnedTags.
References Category, and UPROPERTY().
UPROPERTY() [4/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
How many bits to use for "number of tags" in FMinimalReplicationTagCountMap::NetSerialize.
References Advanced, Category, and UPROPERTY().
UPROPERTY() [5/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
Whether the game should allow the usage of gameplay mod evaluation channels or not.
References Category, config, meta, and UPROPERTY().
UPROPERTY() [6/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
The default mod evaluation channel for the game.
References Category, config, meta, and UPROPERTY().
UPROPERTY() [7/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
TryActive failed due to GameplayAbility's CanActivateAbility function (Blueprint or Native)
References Category, meta, and UPROPERTY().
UPROPERTY() [8/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
TryActivate failed due to being on cooldown.
References Category, meta, and UPROPERTY().
UPROPERTY() [9/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
TryActivate failed due to not being able to spend costs.
References Category, meta, and UPROPERTY().
UPROPERTY() [10/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
Failed to activate due to invalid networking settings, this is designer error.
References Category, meta, and UPROPERTY().
UPROPERTY() [11/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
TryActivate failed due to being blocked by other abilities.
References Category, meta, and UPROPERTY().
UPROPERTY() [12/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
TryActivate failed due to missing required tags.
References Category, meta, and UPROPERTY().
UPROPERTY() [13/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
Game-specified named aliases for gameplay mod evaluation channels; Only those with valid aliases are eligible to be used in a game (except Channel0, which is always valid)
References Category, config, meta, and UPROPERTY().
UPROPERTY() [14/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
Class reference to gameplay cue manager.
Use this if you want to just instantiate a class for your gameplay cue manager without having to create an asset.
References Category, meta, StaticClass(), and UPROPERTY().
UPROPERTY() [15/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
The class to instantiate as the GameplayTagResponseTable.
References Category, meta, and UPROPERTY().
UPROPERTY() [16/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
Holds information about the valid attributes' min and max values and stacking rules.
References Attribute, Category, meta, and UPROPERTY().
UPROPERTY() [17/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
Name of global curve table to use as the default for scalable floats, etc.
References Category, meta, and UPROPERTY().
UPROPERTY() [18/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
Class reference to gameplay cue manager.
Use this if you want to just instantiate a class for your gameplay cue manager without having to create an asset.
References Category, meta, and UPROPERTY().
UPROPERTY() [19/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
Array of curve table names to use for default values for attribute sets, keyed off of Name/Levels.
References Attribute, Category, and meta.
UPROPERTY() [20/20]
UGameplayAbilitiesDeveloperSettings::UPROPERTY () private
Look in these paths for GameplayCueNotifies.
These are your "always loaded" set.
References Category, meta, and UPROPERTY().
The documentation for this class was generated from the following file:
GameplayAbilitiesDeveloperSettings.h