Unreal Engine 5.6 C++ API: UE::AnimNext::FEvaluationProgram Struct Reference
UE::AnimNext::FEvaluationProgram Struct Reference
#include "EvaluationProgram.h"
Public Member Functions
FEvaluationProgram ()=default
FEvaluationProgram (FEvaluationProgram &&)=default
template<class TaskType>
void AppendTask (TaskType &&Task)
template<class TaskType>
void AppendTaskPtr (const TSharedPtr< TaskType > &TaskPtr)
ANIMNEXTANIMGRAPH_API void Execute (FEvaluationVM &VM) const
ANIMNEXTANIMGRAPH_API bool IsEmpty () const
FEvaluationProgram & operator= (FEvaluationProgram &&)=default
ANIMNEXTANIMGRAPH_API FString ToString () const
Private Member Functions
FEvaluationProgram (const FEvaluationProgram &)=delete
FEvaluationProgram & operator= (const FEvaluationProgram &)=delete
Private Attributes
TArray< TSharedPtr< FAnimNextEvaluationTask > > Tasks
Friends
struct ::FSerializableEvaluationProgram
Detailed Description
Definition at line 27 of file EvaluationProgram.h.
Constructor & Destructor Documentation
FEvaluationProgram() [1/3]
UE::AnimNext::FEvaluationProgram::FEvaluationProgram () default
Referenced by FEvaluationProgram(), FEvaluationProgram(), operator=(), and operator=().
FEvaluationProgram() [2/3]
UE::AnimNext::FEvaluationProgram::FEvaluationProgram (FEvaluationProgram &&) default
References FEvaluationProgram().
FEvaluationProgram() [3/3]
UE::AnimNext::FEvaluationProgram::FEvaluationProgram (const FEvaluationProgram &) private delete
References FEvaluationProgram().
Member Function Documentation
AppendTask()
template<class TaskType> void UE::AnimNext::FEvaluationProgram::AppendTask (TaskType && Task) inline
Definition at line 68 of file EvaluationProgram.h.
References MakeShared(), MoveTemp(), and Tasks.
AppendTaskPtr()
template<class TaskType> void UE::AnimNext::FEvaluationProgram::AppendTaskPtr (const TSharedPtr< TaskType > & TaskPtr) inline
Definition at line 78 of file EvaluationProgram.h.
References Tasks.
Execute()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FEvaluationProgram::Execute (FEvaluationVM & VM) const
References UE_API.
IsEmpty()
ANIMNEXTANIMGRAPH_API bool UE::AnimNext::FEvaluationProgram::IsEmpty () const
References UE_API.
operator=() [1/2]
FEvaluationProgram & UE::AnimNext::FEvaluationProgram::operator= (const FEvaluationProgram &) private delete
References FEvaluationProgram().
operator=() [2/2]
FEvaluationProgram & UE::AnimNext::FEvaluationProgram::operator= (FEvaluationProgram &&) default
References FEvaluationProgram().
ToString()
ANIMNEXTANIMGRAPH_API FString UE::AnimNext::FEvaluationProgram::ToString () const
References UE_API.
Friends And Related Symbol Documentation
::FSerializableEvaluationProgram
friend struct ::FSerializableEvaluationProgram friend
Definition at line 54 of file EvaluationProgram.h.
Field Documentation
Tasks
TArray<TSharedPtr<FAnimNextEvaluationTask> > UE::AnimNext::FEvaluationProgram::Tasks private
Definition at line 61 of file EvaluationProgram.h.
Referenced by AppendTask(), and AppendTaskPtr().
The documentation for this struct was generated from the following file:
EvaluationProgram.h