Unreal Engine 5.6 C++ API: FSceneViewExtensionContext Struct Reference
FSceneViewExtensionContext Struct Reference
Contains information about the context in which this scene view extension will be used.
#include "SceneViewExtensionContext.h"
Public Member Functions
FSceneViewExtensionContext ()
FSceneViewExtensionContext (FSceneInterface *InScene)
FSceneViewExtensionContext (FViewport *InViewport)
virtual ~FSceneViewExtensionContext ()
UWorld * GetWorld () const
Retrieve the world pointer for this context.
bool IsA (const FSceneViewExtensionContext &&Other) const
virtual bool IsHMDSupported () const
bool IsStereoSupported () const
Data Fields
bool bStereoEnabled = false
FSceneInterface * Scene = nullptr
FViewport * Viewport = nullptr
Private Member Functions
virtual FName GetRTTI () const
Detailed Description
Contains information about the context in which this scene view extension will be used.
Definition at line 19 of file SceneViewExtensionContext.h.
Constructor & Destructor Documentation
FSceneViewExtensionContext() [1/3]
FSceneViewExtensionContext::FSceneViewExtensionContext () inline
Definition at line 32 of file SceneViewExtensionContext.h.
References Scene, and Viewport.
Referenced by FDisplayClusterSceneViewExtensionContext::FDisplayClusterSceneViewExtensionContext(), FDisplayClusterSceneViewExtensionContext::FDisplayClusterSceneViewExtensionContext(), FDisplayClusterSceneViewExtensionContext::FDisplayClusterSceneViewExtensionContext(), and IsA().
FSceneViewExtensionContext() [2/3]
FSceneViewExtensionContext::FSceneViewExtensionContext (FViewport * InViewport) inline explicit
Definition at line 33 of file SceneViewExtensionContext.h.
References Viewport.
FSceneViewExtensionContext() [3/3]
FSceneViewExtensionContext::FSceneViewExtensionContext (FSceneInterface * InScene) inline explicit
Definition at line 34 of file SceneViewExtensionContext.h.
References Scene.
~FSceneViewExtensionContext()
virtual FSceneViewExtensionContext::~FSceneViewExtensionContext () inline virtual
Definition at line 36 of file SceneViewExtensionContext.h.
Member Function Documentation
GetRTTI()
virtual FName FSceneViewExtensionContext::GetRTTI () const inline private virtual
Reimplemented in FDisplayClusterSceneViewExtensionContext.
Definition at line 23 of file SceneViewExtensionContext.h.
References TEXT.
Referenced by IsA().
GetWorld()
UWorld * FSceneViewExtensionContext::GetWorld () const inline
Retrieve the world pointer for this context.
Definition at line 45 of file SceneViewExtensionContext.h.
References Scene, and Viewport.
IsA()
bool FSceneViewExtensionContext::IsA (const FSceneViewExtensionContext && Other) const inline
Definition at line 39 of file SceneViewExtensionContext.h.
References FSceneViewExtensionContext(), GetRTTI(), and Other.
IsHMDSupported()
virtual bool FSceneViewExtensionContext::IsHMDSupported () const inline virtual
Reimplemented in FDisplayClusterSceneViewExtensionContext.
Definition at line 69 of file SceneViewExtensionContext.h.
IsStereoSupported()
bool FSceneViewExtensionContext::IsStereoSupported () const inline
Definition at line 63 of file SceneViewExtensionContext.h.
References bStereoEnabled, GEngine, and Viewport.
Field Documentation
bStereoEnabled
bool FSceneViewExtensionContext::bStereoEnabled = false
Definition at line 30 of file SceneViewExtensionContext.h.
Referenced by IsStereoSupported().
Scene
FSceneInterface* FSceneViewExtensionContext::Scene = nullptr
Definition at line 29 of file SceneViewExtensionContext.h.
Referenced by FSceneViewExtensionContext(), FSceneViewExtensionContext(), and GetWorld().
Viewport
FViewport* FSceneViewExtensionContext::Viewport = nullptr
Definition at line 28 of file SceneViewExtensionContext.h.
Referenced by FSceneViewExtensionContext(), FSceneViewExtensionContext(), GetWorld(), and IsStereoSupported().
The documentation for this struct was generated from the following file:
SceneViewExtensionContext.h