Unreal Engine 5.6 C++ API: Audio::FQuartzCrossThreadMessage Class Reference
Audio::FQuartzCrossThreadMessage Class Reference
#include "QuartzQuantizationUtilities.h"
Public Member Functions
FQuartzCrossThreadMessage (bool bAutoStartTimer=true)
double GetCurrentTimeMilliseconds () const
double GetResultsMilliseconds () const
double RequestReceived () const
void RequestSent ()
Public Member Functions inherited from Audio::FQuartzLatencyTimer
FQuartzLatencyTimer ()
double GetCurrentTimePassedMs ()
double GetResultsMilliseconds ()
bool HasTimerRun ()
bool HasTimerStarted ()
bool HasTimerStopped ()
bool IsTimerRunning ()
void ResetTimer ()
void StartTimer ()
void StopTimer ()
Private Attributes
FQuartzLatencyTimer Timer
Detailed Description
Definition at line 380 of file QuartzQuantizationUtilities.h.
Constructor & Destructor Documentation
FQuartzCrossThreadMessage()
Audio::FQuartzCrossThreadMessage::FQuartzCrossThreadMessage (bool bAutoStartTimer = true)
Definition at line 732 of file QuartzQuantizationUtilities.cpp.
References Timer.
Member Function Documentation
GetCurrentTimeMilliseconds()
double Audio::FQuartzCrossThreadMessage::GetCurrentTimeMilliseconds () const
Definition at line 756 of file QuartzQuantizationUtilities.cpp.
References Timer.
GetResultsMilliseconds()
double Audio::FQuartzCrossThreadMessage::GetResultsMilliseconds () const
Definition at line 751 of file QuartzQuantizationUtilities.cpp.
References Timer.
Referenced by RequestReceived().
RequestReceived()
double Audio::FQuartzCrossThreadMessage::RequestReceived () const
Definition at line 745 of file QuartzQuantizationUtilities.cpp.
References GetResultsMilliseconds(), and Timer.
Referenced by FQuartzTickableObject::OnCommandEvent(), FQuartzTickableObject::OnMetronomeEvent(), and Audio::IQuartzQuantizedCommand::OnQueued().
RequestSent()
void Audio::FQuartzCrossThreadMessage::RequestSent ()
Definition at line 740 of file QuartzQuantizationUtilities.cpp.
References Timer.
Field Documentation
Timer
FQuartzLatencyTimer Audio::FQuartzCrossThreadMessage::Timer mutable private
Definition at line 394 of file QuartzQuantizationUtilities.h.
Referenced by FQuartzCrossThreadMessage(), GetCurrentTimeMilliseconds(), GetResultsMilliseconds(), RequestReceived(), and RequestSent().
The documentation for this class was generated from the following files:
QuartzQuantizationUtilities.h
QuartzQuantizationUtilities.cpp