Unreal Engine 5.6 C++ API: UE::Geometry::TConvexHull3< RealType > Class Template Reference
UE::Geometry::TConvexHull3< RealType > Class Template Reference
Calculate the Convex Hull of a 3D point set as a Triangle Mesh.
#include "ConvexHull3.h"
Public Types
using FPolygonFace = TArray<int32, TInlineAllocator<8>>
Public Member Functions
void Empty ()
Empty any previously-computed convex hull data.
template<typename VectorType>
TArray< THalfspace3< RealType > > GetAsHalfspaces (TArrayView< const VectorType > Points) const
Convert an already-computed convex hull into a halfspace representation Following the logic of ContainmentQueries3.h, all halfspaces are oriented "outwards," so a point is inside the convex hull if it is outside of all halfspaces in the array.
template<typename VectorType>
TArray< THalfspace3< RealType > > GetAsHalfspaces (TFunctionRef< VectorType(int32)> GetPointFunc) const
Convert an already-computed convex hull into a halfspace representation Following the logic of ContainmentQueries3.h, all halfspaces are oriented "outwards," so a point is inside the convex hull if it is outside of all halfspaces in the array.
int GetDimension () const
Number of dimensions spanned by the input points.
GEOMETRYCORE_API void GetFaces (TFunctionRef< void(TArray< int32 > &, TVector< RealType >)> PolygonFunc, TFunctionRef< TVector< RealType >(int32)> GetPointFunc) const
Get faces of the convex hull as convex polygons, merging faces that are exactly coplanar.
TLine3< RealType > const & GetLine () const
int GetNumHullPoints () const
TPlane3< RealType > const & GetPlane () const
GEOMETRYCORE_API void GetSimplifiedFaces (TArray< FPolygonFace > &OutPolygons, TFunctionRef< TVector< RealType >(int32)> GetPointFunc, RealType FaceAngleToleranceInDegrees=(RealType) 1.0, RealType PlaneDistanceTolerance=(RealType) 1.0, TArray< TVector< RealType > > *OutPolygonNormals=nullptr) const
Get faces of the convex hull as convex polygons, simplifying the hull by merging near-coplanar faces and only keeping vertices that are on the corner of at least three merged faces.
GEOMETRYCORE_API void GetSimplifiedFaces (TFunctionRef< void(TArray< int32 > &, TVector< RealType >)> PolygonFunc, TFunctionRef< TVector< RealType >(int32)> GetPointFunc, RealType FaceAngleToleranceInDegrees=(RealType) 1.0, RealType PlaneDistanceTolerance=(RealType) 1.0) const
Get faces of the convex hull as convex polygons, simplifying the hull by merging near-coplanar faces and only keeping vertices that are on the corner of at least three merged faces.
TArray< FIndex3i > const & GetTriangleNeighbors () const
Only valid if bSaveTriangleNeighbors was true when Solve() was called.
TArray< FIndex3i > const & GetTriangles () const
void GetTriangles (TFunctionRef< void(FIndex3i)> TriangleFunc)
Call TriangleFunc for each triangle of the Convex Hull.
bool IsSolutionAvailable () const
TArray< FIndex3i > && MoveTriangles ()
bool Solve (int32 NumPoints, TFunctionRef< TVector< RealType >(int32)> GetPointFunc)
GEOMETRYCORE_API bool Solve (int32 NumPoints, TFunctionRef< TVector< RealType >(int32)> GetPointFunc, TFunctionRef< bool(int32)> FilterFunc)
Generate convex hull as long as input is not degenerate If input is degenerate, this will return false, and caller can call GetDimension() to determine whether the points were coplanar, collinear, or all the same point.
template<typename VectorType>
bool Solve (TArrayView< const VectorType > Points)
Generate convex hull as long as input is not degenerate If input is degenerate, this will return false, and caller can call GetDimension() to determine whether the points were collinear, or all the same point.
template<typename VectorType>
bool Solve (TArrayView< const VectorType > Points, TFunctionRef< bool(int32)> FilterFunc)
Generate convex hull as long as input is not degenerate If input is degenerate, this will return false, and caller can call GetDimension() to determine whether the points were collinear, or all the same point.
Static Public Member Functions
static GEOMETRYCORE_API double ComputeVolume (const TArrayView< const TVector< RealType > > Vertices)
static void WalkBorder (const TArray< FIndex3i > &Triangles, const TArray< FIndex3i > &TriangleNeighbors, TFunctionRef< bool(int32)> InGroupFunc, int32 StartIdx, TArray< int32 > &OutBorderVertexIndices)
Data Fields
bool bSaveTriangleNeighbors = false
Whether neighbors for the hull triangles should be computed/saved.
FProgressCancel * Progress = nullptr
Set this to be able to cancel running operation.
TConvexHullSimplificationSettings< RealType > SimplificationSettings
Protected Attributes
int32 Dimension
TArray< FIndex3i > Hull
TArray< FIndex3i > HullNeighbors
TLine3< RealType > Line
int NumHullPoints = 0
TPlane3< RealType > Plane
Detailed Description
template<typename RealType>
class UE::Geometry::TConvexHull3< RealType >
Calculate the Convex Hull of a 3D point set as a Triangle Mesh.
Definition at line 76 of file ConvexHull3.h.
Member Typedef Documentation
FPolygonFace
template<typename RealType> using UE::Geometry::TConvexHull3< RealType >::FPolygonFace = TArray<int32, TInlineAllocator<8>>
Definition at line 184 of file ConvexHull3.h.
Member Function Documentation
ComputeVolume()
template<typename RealType> GEOMETRYCORE_API double UE::Geometry::TConvexHull3< RealType >::ComputeVolume (const TArrayView< const TVector< RealType > > Vertices) static
Empty()
template<typename RealType> void UE::Geometry::TConvexHull3< RealType >::Empty () inline
Empty any previously-computed convex hull data.
Frees the hull memory. Note: You do not need to call this before calling Generate() with new data.
Definition at line 257 of file ConvexHull3.h.
GetAsHalfspaces() [1/2]
template<typename RealType> template<typename VectorType> TArray< THalfspace3< RealType > > UE::Geometry::TConvexHull3< RealType >::GetAsHalfspaces (TArrayView< const VectorType > Points) const inline
Convert an already-computed convex hull into a halfspace representation Following the logic of ContainmentQueries3.h, all halfspaces are oriented "outwards," so a point is inside the convex hull if it is outside of all halfspaces in the array.
Parameters
Points Array of points to consider
Returns
Array of halfspaces
Definition at line 222 of file ConvexHull3.h.
GetAsHalfspaces() [2/2]
template<typename RealType> template<typename VectorType> TArray< THalfspace3< RealType > > UE::Geometry::TConvexHull3< RealType >::GetAsHalfspaces (TFunctionRef< VectorType(int32)> GetPointFunc) const inline
Convert an already-computed convex hull into a halfspace representation Following the logic of ContainmentQueries3.h, all halfspaces are oriented "outwards," so a point is inside the convex hull if it is outside of all halfspaces in the array.
Parameters
GetPointFunc Function providing array-style access into points
Returns
Array of halfspaces
Definition at line 242 of file ConvexHull3.h.
GetDimension()
template<typename RealType> int UE::Geometry::TConvexHull3< RealType >::GetDimension () const inline
Number of dimensions spanned by the input points.
Definition at line 267 of file ConvexHull3.h.
GetFaces()
template<typename RealType> GEOMETRYCORE_API void UE::Geometry::TConvexHull3< RealType >::GetFaces (TFunctionRef< void(TArray< int32 > &, TVector< RealType >)> PolygonFunc, TFunctionRef< TVector< RealType >(int32)> GetPointFunc) const
Get faces of the convex hull as convex polygons, merging faces that are exactly coplanar.
Parameters
PolygonFunc Callback to be called for each polygon, with the array of vertex indices and the face normal
GetPointFunc Function providing array-style access into points
GetLine()
template<typename RealType> TLine3< RealType > const & UE::Geometry::TConvexHull3< RealType >::GetLine () const inline
Returns
If GetDimension() returns 1, this returns the line the data was on. Otherwise result is not meaningful.
Definition at line 272 of file ConvexHull3.h.
GetNumHullPoints()
template<typename RealType> int UE::Geometry::TConvexHull3< RealType >::GetNumHullPoints () const inline
Returns
Number of points on the output hull
Definition at line 283 of file ConvexHull3.h.
GetPlane()
template<typename RealType> TPlane3< RealType > const & UE::Geometry::TConvexHull3< RealType >::GetPlane () const inline
Returns
If GetDimension() returns 2, this returns the plane the data was on. Otherwise result is not meaningful.
Definition at line 277 of file ConvexHull3.h.
GetSimplifiedFaces() [1/2]
template<typename RealType> GEOMETRYCORE_API void UE::Geometry::TConvexHull3< RealType >::GetSimplifiedFaces (TArray< FPolygonFace > & OutPolygons, TFunctionRef< TVector< RealType >(int32)> GetPointFunc, RealType FaceAngleToleranceInDegrees = (RealType) 1.0, RealType PlaneDistanceTolerance = (RealType) 1.0, TArray< TVector< RealType > > * OutPolygonNormals = nullptr) const
Get faces of the convex hull as convex polygons, simplifying the hull by merging near-coplanar faces and only keeping vertices that are on the corner of at least three merged faces.
Parameters
OutPolygons Polygons of the convex hull faces, as arrays of indices into the original points
GetPointFunc Function providing array-style access into points
FaceAngleToleranceInDegrees The hull will be simplified by merging faces with less than this dihedral angle between them
PlaneDistanceTolerance Faces will not merge unless all points on the face are within this distance of the combined (average) face plane
OutPolygonNormals Optional array of normals for each polygon
GetSimplifiedFaces() [2/2]
template<typename RealType> GEOMETRYCORE_API void UE::Geometry::TConvexHull3< RealType >::GetSimplifiedFaces (TFunctionRef< void(TArray< int32 > &, TVector< RealType >)> PolygonFunc, TFunctionRef< TVector< RealType >(int32)> GetPointFunc, RealType FaceAngleToleranceInDegrees = (RealType) 1.0, RealType PlaneDistanceTolerance = (RealType) 1.0) const
Get faces of the convex hull as convex polygons, simplifying the hull by merging near-coplanar faces and only keeping vertices that are on the corner of at least three merged faces.
Parameters
PolygonFunc Callback to be called for each polygon, with the array of vertex indices and the face normal
GetPointFunc Function providing array-style access into points
FaceAngleToleranceInDegrees The hull will be simplified by merging faces with less than this dihedral angle between them
PlaneDistanceTolerance Faces will not merge unless all points on the face are within this distance of the combined (average) face plane
GetTriangleNeighbors()
template<typename RealType> TArray< FIndex3i > const & UE::Geometry::TConvexHull3< RealType >::GetTriangleNeighbors () const inline
Only valid if bSaveTriangleNeighbors was true when Solve() was called.
Returns
Neighbors of each hull triangle, in edge order – i.e., Nbr.A is the triangle across edge(Tri.A, Tri.B)
Definition at line 201 of file ConvexHull3.h.
GetTriangles() [1/2]
template<typename RealType> TArray< FIndex3i > const & UE::Geometry::TConvexHull3< RealType >::GetTriangles () const inline
Returns
convex hull triangles
Definition at line 160 of file ConvexHull3.h.
GetTriangles() [2/2]
template<typename RealType> void UE::Geometry::TConvexHull3< RealType >::GetTriangles (TFunctionRef< void(FIndex3i)> TriangleFunc) inline
Call TriangleFunc for each triangle of the Convex Hull.
The triangles index into the point set passed to Solve()
Definition at line 151 of file ConvexHull3.h.
IsSolutionAvailable()
template<typename RealType> bool UE::Geometry::TConvexHull3< RealType >::IsSolutionAvailable () const inline
Returns
true if convex hull is available
Definition at line 143 of file ConvexHull3.h.
MoveTriangles()
template<typename RealType> TArray< FIndex3i > && UE::Geometry::TConvexHull3< RealType >::MoveTriangles () inline
Returns
convex hull triangles by a move
Definition at line 208 of file ConvexHull3.h.
Solve() [1/4]
template<typename RealType> bool UE::Geometry::TConvexHull3< RealType >::Solve (int32 NumPoints, TFunctionRef< TVector< RealType >(int32)> GetPointFunc) inline
Definition at line 101 of file ConvexHull3.h.
Solve() [2/4]
template<typename RealType> GEOMETRYCORE_API bool UE::Geometry::TConvexHull3< RealType >::Solve (int32 NumPoints, TFunctionRef< TVector< RealType >(int32)> GetPointFunc, TFunctionRef< bool(int32)> FilterFunc)
Generate convex hull as long as input is not degenerate If input is degenerate, this will return false, and caller can call GetDimension() to determine whether the points were coplanar, collinear, or all the same point.
Parameters
NumPoints Number of points to consider
GetPointFunc Function providing array-style access into points
FilterFunc Optional filter to include only a subset of the points in the output hull
Returns
true if hull was generated, false if points span < 2 dimensions
Referenced by UE::Geometry::TConvexHull3< float >::Solve(), UE::Geometry::TConvexHull3< float >::Solve(), and UE::Geometry::TConvexHull3< float >::Solve().
Solve() [3/4]
template<typename RealType> template<typename VectorType> bool UE::Geometry::TConvexHull3< RealType >::Solve (TArrayView< const VectorType > Points) inline
Generate convex hull as long as input is not degenerate If input is degenerate, this will return false, and caller can call GetDimension() to determine whether the points were collinear, or all the same point.
Parameters
Points Array of points to consider
Returns
true if hull was generated, false if points span < 2 dimensions
Definition at line 134 of file ConvexHull3.h.
Solve() [4/4]
template<typename RealType> template<typename VectorType> bool UE::Geometry::TConvexHull3< RealType >::Solve (TArrayView< const VectorType > Points, TFunctionRef< bool(int32)> FilterFunc) inline
Generate convex hull as long as input is not degenerate If input is degenerate, this will return false, and caller can call GetDimension() to determine whether the points were collinear, or all the same point.
Parameters
Points Array of points to consider
FilterFunc Optional filter to include only a subset of the points in the output hull
Returns
true if hull was generated, false if points span < 2 dimensions
Definition at line 116 of file ConvexHull3.h.
WalkBorder()
template<typename RealType> void UE::Geometry::TConvexHull3< RealType >::WalkBorder (const TArray< FIndex3i > & Triangles, const TArray< FIndex3i > & TriangleNeighbors, TFunctionRef< bool(int32)> InGroupFunc, int32 StartIdx, TArray< int32 > & OutBorderVertexIndices) static
Field Documentation
bSaveTriangleNeighbors
template<typename RealType> bool UE::Geometry::TConvexHull3< RealType >::bSaveTriangleNeighbors = false
Whether neighbors for the hull triangles should be computed/saved.
If true, can call GetTriangleNeighbors() after Solve().
Definition at line 82 of file ConvexHull3.h.
Dimension
template<typename RealType> int32 UE::Geometry::TConvexHull3< RealType >::Dimension protected
Definition at line 298 of file ConvexHull3.h.
Hull
template<typename RealType> TArray<FIndex3i> UE::Geometry::TConvexHull3< RealType >::Hull protected
Definition at line 303 of file ConvexHull3.h.
HullNeighbors
template<typename RealType> TArray<FIndex3i> UE::Geometry::TConvexHull3< RealType >::HullNeighbors protected
Definition at line 305 of file ConvexHull3.h.
Line
template<typename RealType> TLine3<RealType> UE::Geometry::TConvexHull3< RealType >::Line protected
Definition at line 299 of file ConvexHull3.h.
NumHullPoints
template<typename RealType> int UE::Geometry::TConvexHull3< RealType >::NumHullPoints = 0 protected
Definition at line 302 of file ConvexHull3.h.
Plane
template<typename RealType> TPlane3<RealType> UE::Geometry::TConvexHull3< RealType >::Plane protected
Definition at line 300 of file ConvexHull3.h.
Progress
template<typename RealType> FProgressCancel* UE::Geometry::TConvexHull3< RealType >::Progress = nullptr
Set this to be able to cancel running operation.
Definition at line 290 of file ConvexHull3.h.
SimplificationSettings
template<typename RealType> TConvexHullSimplificationSettings<RealType> UE::Geometry::TConvexHull3< RealType >::SimplificationSettings
Definition at line 85 of file ConvexHull3.h.
The documentation for this class was generated from the following file:
ConvexHull3.h