Unreal Engine 5.6 C++ API: UE::Landscape::EditLayers::FOutputWorldArea Class Reference
UE::Landscape::EditLayers::FOutputWorldArea Class Reference
Describes the output area needed where a given edit layer renderer's render item writes: this allows to define the components of landscape that need to be processed and allows to divide the work into batches.
#include "LandscapeEditLayerRenderer.h"
Public Types
enum class EType { LocalComponent , SpecificComponent , OOBox }
Public Member Functions
FBox ComputeWorldAreaAABB (const FTransform &InComponentTransform, const FBox &InComponentLocalBounds) const
FOOBox2D ComputeWorldAreaOOBB (const FTransform &InComponentTransform, const FBox &InComponentLocalBounds) const
const FOOBox2D & GetOOBox () const
In the EType::OOBox case, returns the OOBox.
const FIntPoint & GetSpecificComponentKey () const
In the EType::SpecificComponent case, returns the component's coordinates.
EType GetType () const
const FOOBox2D * TryGetOOBox () const
Static Public Member Functions
static FOutputWorldArea CreateLocalComponent ()
static FOutputWorldArea CreateOOBox (const FOOBox2D &InOOBox)
static FOutputWorldArea CreateSpecificComponent (const FIntPoint &InComponentKey)
Private Member Functions
FOutputWorldArea (EType InType, const FIntPoint &InComponentKey=FIntPoint(ForceInit), const FOOBox2D &InOOBox=FOOBox2D())
Private Attributes
FOOBox2D OOBox2D
World space Object-oriented box in the EType::OOBBox case.
FIntPoint SpecificComponentKey = FIntPoint(ForceInit)
Coordinates of the component (see ULandscapeComponent::GetComponentKey()) in the EType::SpecificComponent case.
EType Type = EType::LocalComponent
Detailed Description
Describes the output area needed where a given edit layer renderer's render item writes: this allows to define the components of landscape that need to be processed and allows to divide the work into batches.
Definition at line 123 of file LandscapeEditLayerRenderer.h.
Member Enumeration Documentation
EType
enum class UE::Landscape::EditLayers::FOutputWorldArea::EType strong
Enumerator
LocalComponent
SpecificComponent
OOBox
Definition at line 126 of file LandscapeEditLayerRenderer.h.
Constructor & Destructor Documentation
FOutputWorldArea()
UE::Landscape::EditLayers::FOutputWorldArea::FOutputWorldArea (EType InType, const FIntPoint & InComponentKey = FIntPoint(ForceInit), const FOOBox2D & InOOBox = FOOBox2D()) inline private
Definition at line 148 of file LandscapeEditLayerRenderer.h.
References ForceInit, OOBox2D, SpecificComponentKey, and Type.
Referenced by CreateLocalComponent(), CreateOOBox(), and CreateSpecificComponent().
Member Function Documentation
ComputeWorldAreaAABB()
FBox UE::Landscape::EditLayers::FOutputWorldArea::ComputeWorldAreaAABB (const FTransform & InComponentTransform, const FBox & InComponentLocalBounds) const
ComputeWorldAreaOOBB()
FOOBox2D UE::Landscape::EditLayers::FOutputWorldArea::ComputeWorldAreaOOBB (const FTransform & InComponentTransform, const FBox & InComponentLocalBounds) const
CreateLocalComponent()
FOutputWorldArea UE::Landscape::EditLayers::FOutputWorldArea::CreateLocalComponent () inline static
Definition at line 133 of file LandscapeEditLayerRenderer.h.
References FOutputWorldArea(), and LocalComponent.
CreateOOBox()
FOutputWorldArea UE::Landscape::EditLayers::FOutputWorldArea::CreateOOBox (const FOOBox2D & InOOBox) inline static
Definition at line 135 of file LandscapeEditLayerRenderer.h.
References FOutputWorldArea(), ForceInit, and OOBox.
CreateSpecificComponent()
FOutputWorldArea UE::Landscape::EditLayers::FOutputWorldArea::CreateSpecificComponent (const FIntPoint & InComponentKey) inline static
Definition at line 134 of file LandscapeEditLayerRenderer.h.
References FOutputWorldArea(), and SpecificComponent.
GetOOBox()
const FOOBox2D & UE::Landscape::EditLayers::FOutputWorldArea::GetOOBox () const inline
In the EType::OOBox case, returns the OOBox.
Definition at line 141 of file LandscapeEditLayerRenderer.h.
References check, OOBox, OOBox2D, and Type.
GetSpecificComponentKey()
const FIntPoint & UE::Landscape::EditLayers::FOutputWorldArea::GetSpecificComponentKey () const inline
In the EType::SpecificComponent case, returns the component's coordinates.
Definition at line 139 of file LandscapeEditLayerRenderer.h.
References check, SpecificComponent, SpecificComponentKey, and Type.
GetType()
EType UE::Landscape::EditLayers::FOutputWorldArea::GetType () const inline
Definition at line 137 of file LandscapeEditLayerRenderer.h.
References Type.
TryGetOOBox()
const FOOBox2D * UE::Landscape::EditLayers::FOutputWorldArea::TryGetOOBox () const inline
Definition at line 142 of file LandscapeEditLayerRenderer.h.
References OOBox, OOBox2D, and Type.
Field Documentation
OOBox2D
FOOBox2D UE::Landscape::EditLayers::FOutputWorldArea::OOBox2D private
World space Object-oriented box in the EType::OOBBox case.
Definition at line 159 of file LandscapeEditLayerRenderer.h.
Referenced by FOutputWorldArea(), GetOOBox(), and TryGetOOBox().
SpecificComponentKey
FIntPoint UE::Landscape::EditLayers::FOutputWorldArea::SpecificComponentKey = FIntPoint(ForceInit) private
Coordinates of the component (see ULandscapeComponent::GetComponentKey()) in the EType::SpecificComponent case.
Definition at line 157 of file LandscapeEditLayerRenderer.h.
Referenced by FOutputWorldArea(), and GetSpecificComponentKey().
Type
EType UE::Landscape::EditLayers::FOutputWorldArea::Type = EType::LocalComponent private
Definition at line 155 of file LandscapeEditLayerRenderer.h.
Referenced by FOutputWorldArea(), GetOOBox(), GetSpecificComponentKey(), GetType(), and TryGetOOBox().
The documentation for this class was generated from the following file:
LandscapeEditLayerRenderer.h