Unreal Engine 5.6 C++ API: UE::DisplayClusterViewportHelpers Namespace Reference
UE::DisplayClusterViewportHelpers Namespace Reference
Helper functions for the DisplayClusterViewport.
Functions
template<class TComp>
const TComp & GetMatchingComponentFromRootActor (const IDisplayClusterViewportConfiguration &InConfiguration, const EDisplayClusterRootActorType InRootActorType, const TComp &InComponent)
Return the same component (by class and name) from a DCRA of the specified type.
template<class TComp>
TComp * GetOwnerRootActorComponentByName (USceneComponent *ComponentOfRootActor, const FString &InComponentName)
Find a component by name from a RootActor of the specified type.
template<class TComp>
TComp * GetRootActorComponentByName (const IDisplayClusterViewportConfiguration &InConfiguration, const EDisplayClusterRootActorType InRootActorType, const FString &InComponentName)
Find a component by name from a RootActor of the specified type.
Detailed Description
Helper functions for the DisplayClusterViewport.
Function Documentation
GetMatchingComponentFromRootActor()
template<class TComp> const TComp & UE::DisplayClusterViewportHelpers::GetMatchingComponentFromRootActor (const IDisplayClusterViewportConfiguration & InConfiguration, const EDisplayClusterRootActorType InRootActorType, const TComp & InComponent)
Return the same component (by class and name) from a DCRA of the specified type.
If no other component exists, or if the current DCRA type matches the requested one, the input component is returned.
Parameters
InRootActorType - the search is performed within the DCRA of the given type.
InComponent - The component that is used for the search.
Returns
A component with the same name and class belonging to a DCRA of this type.
Definition at line 79 of file DisplayClusterViewportHelpers.h.
References IDisplayClusterViewportConfiguration::GetRootActor().
GetOwnerRootActorComponentByName()
template<class TComp> TComp * UE::DisplayClusterViewportHelpers::GetOwnerRootActorComponentByName (USceneComponent * ComponentOfRootActor, const FString & InComponentName)
Find a component by name from a RootActor of the specified type.
Parameters
ComponentOfRootActor
InComponentName - the name of the component
Definition at line 45 of file DisplayClusterViewportHelpers.h.
References Cast(), and UActorComponent::GetOwner().
GetRootActorComponentByName()
template<class TComp> TComp * UE::DisplayClusterViewportHelpers::GetRootActorComponentByName (const IDisplayClusterViewportConfiguration & InConfiguration, const EDisplayClusterRootActorType InRootActorType, const FString & InComponentName)
Find a component by name from a RootActor of the specified type.
Parameters
InConfiguration - current configuration
InRootActorType - the search is performed within the DCRA of the given type.
InComponentName - the name of the component
Definition at line 21 of file DisplayClusterViewportHelpers.h.
References Component, and IDisplayClusterViewportConfiguration::GetRootActor().