Unreal Engine 5.6 C++ API: HashTable.h File Reference
HashTable.h File Reference
#include "Containers/ContainerAllocationPolicies.h"
#include "CoreTypes.h"
#include "HAL/PlatformAtomics.h"
#include "HAL/PlatformCrt.h"
#include "HAL/UnrealMemory.h"
#include "Math/UnrealMathUtility.h"
#include "Misc/AssertionMacros.h"
#include "Serialization/MemoryImageWriter.h"
#include "Serialization/MemoryLayout.h"
#include "Templates/UnrealTemplate.h"
#include <initializer_list>
Data Structures
class FHashTable
class THashTable< InAllocator >
class TStaticHashTable< HashSize, IndexSize >
Namespaces
namespace Freeze
Functions
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT (template< typename InAllocator >, THashTable< InAllocator >)
template<typename InAllocator>
uint32 Freeze::IntrinsicAppendHash (const THashTable< InAllocator > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
template<typename InAllocator>
uint32 Freeze::IntrinsicGetTargetAlignment (const THashTable< InAllocator > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams)
template<typename InAllocator>
uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const THashTable< InAllocator > &Object, void *OutDst)
template<typename InAllocator>
void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const THashTable< InAllocator > &Object, const FTypeLayoutDesc &)
FORCEINLINE uint32 Murmur32 (std::initializer_list< uint32 > InitList)
FORCEINLINE uint64 Murmur64 (std::initializer_list< uint64 > InitList)
FORCEINLINE uint32 MurmurFinalize32 (uint32 Hash)
FORCEINLINE uint64 MurmurFinalize64 (uint64 Hash)
Function Documentation
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT()
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT (template< typename InAllocator > , THashTable< InAllocator >)
Murmur32()
FORCEINLINE uint32 Murmur32 (std::initializer_list< uint32 > InitList)
Definition at line 43 of file HashTable.h.
References FORCEINLINE, Hash, and MurmurFinalize32().
Murmur64()
FORCEINLINE uint64 Murmur64 (std::initializer_list< uint64 > InitList)
Definition at line 60 of file HashTable.h.
References FORCEINLINE, Hash, and MurmurFinalize64().
MurmurFinalize32()
FORCEINLINE uint32 MurmurFinalize32 (uint32 Hash)
Definition at line 23 of file HashTable.h.
References FORCEINLINE, and Hash.
Referenced by Murmur32().
MurmurFinalize64()
FORCEINLINE uint64 MurmurFinalize64 (uint64 Hash)
Definition at line 33 of file HashTable.h.
References FORCEINLINE, and Hash.
Referenced by FVirtualTextureLocalTile::GetMurmurHash(), FVirtualTextureLocalTileRequest::GetMurmurHash(), and Murmur64().