Unreal Engine 5.6 C++ API: UE::AnimNext::ITraitInterface Struct Reference
UE::AnimNext::ITraitInterface Struct Reference
ITraitInterface.
#include "ITraitInterface.h"
Public Member Functions
virtual ~ITraitInterface ()
virtual const FText & GetDisplayName () const
virtual const FText & GetDisplayShortName () const
virtual FTraitInterfaceUID GetInterfaceUID () const
virtual bool IsInternal () const
Static Public Attributes
static constexpr FTraitInterfaceUID InterfaceUID = FTraitInterfaceUID::MakeUID(TEXT("ITraitInterface"))
Detailed Description
ITraitInterface.
Base type for all trait interfaces. Used for type safety.
Definition at line 38 of file ITraitInterface.h.
Constructor & Destructor Documentation
~ITraitInterface()
virtual UE::AnimNext::ITraitInterface::~ITraitInterface () inline virtual
Definition at line 40 of file ITraitInterface.h.
Member Function Documentation
GetDisplayName()
virtual const FText & UE::AnimNext::ITraitInterface::GetDisplayName () const inline virtual
Reimplemented in UE::AnimNext::IAlphaInputArgs, UE::AnimNext::IAttributeProvider, UE::AnimNext::IBlendStack, UE::AnimNext::IContinuousBlend, UE::AnimNext::IDiscreteBlend, UE::AnimNext::IEvaluate, UE::AnimNext::IGarbageCollection, UE::AnimNext::IGraphFactory, UE::AnimNext::IGroupSynchronization, UE::AnimNext::IHierarchy, UE::AnimNext::IInertializerBlend, UE::AnimNext::INotifySource, UE::AnimNext::ISmoothBlend, UE::AnimNext::ISmoothBlendPerBone, UE::AnimNext::ITimeline, UE::AnimNext::ITimelinePlayer, UE::AnimNext::IUpdate, and UE::AnimNext::IUpdateTraversal.
Definition at line 55 of file ITraitInterface.h.
References ensure, and FText::GetEmpty().
GetDisplayShortName()
virtual const FText & UE::AnimNext::ITraitInterface::GetDisplayShortName () const inline virtual
Reimplemented in UE::AnimNext::IAlphaInputArgs, UE::AnimNext::IAttributeProvider, UE::AnimNext::IBlendStack, UE::AnimNext::IContinuousBlend, UE::AnimNext::IDiscreteBlend, UE::AnimNext::IEvaluate, UE::AnimNext::IGarbageCollection, UE::AnimNext::IGraphFactory, UE::AnimNext::IGroupSynchronization, UE::AnimNext::IHierarchy, UE::AnimNext::IInertializerBlend, UE::AnimNext::INotifySource, UE::AnimNext::ISmoothBlend, UE::AnimNext::ISmoothBlendPerBone, UE::AnimNext::ITimeline, UE::AnimNext::ITimelinePlayer, UE::AnimNext::IUpdate, and UE::AnimNext::IUpdateTraversal.
Definition at line 57 of file ITraitInterface.h.
References ensure, and FText::GetEmpty().
GetInterfaceUID()
virtual FTraitInterfaceUID UE::AnimNext::ITraitInterface::GetInterfaceUID () const inline virtual
Definition at line 48 of file ITraitInterface.h.
References InterfaceUID.
IsInternal()
virtual bool UE::AnimNext::ITraitInterface::IsInternal () const inline virtual
Reimplemented in UE::AnimNext::IGarbageCollection.
Definition at line 52 of file ITraitInterface.h.
Field Documentation
InterfaceUID
FTraitInterfaceUID UE::AnimNext::ITraitInterface::InterfaceUID = FTraitInterfaceUID::MakeUID(TEXT("ITraitInterface")) static constexpr
Definition at line 45 of file ITraitInterface.h.
Referenced by GetInterfaceUID().
The documentation for this struct was generated from the following file:
ITraitInterface.h